import { ExerciseSeed } from './exerciseData.js';

export const EXERCISES_PART_4: ExerciseSeed[] = [
  // ================= Glúteos =================
  {
    id: 'EX_GLU_001',
    name: 'Elevação pélvica',
    muscle_group: 'Glúteos',
    secondary_muscles: 'Posterior, Core',
    equipment: 'Solo / Halter',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Deitado no solo, eleva o quadril ativando glúteos e estabilização pélvica.',
    instructions: 'Pés na largura dos ombros, empurre os calcanhares e contraia forte o glúteo no topo.',
    default_sets: 3,
    default_min_reps: 12,
    default_max_reps: 15,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_GLU_002',
    name: 'Hip thrust',
    muscle_group: 'Glúteos',
    secondary_muscles: 'Posterior de coxa, Quadríceps',
    equipment: 'Barra / Banco',
    exercise_type: 'Força/Hipertrofia',
    difficulty: 'Intermediário',
    description: 'O principal exercício para hipertrofia e força máxima do glúteo maior.',
    instructions: 'Escápulas apoiadas no banco, barra acolchoada sobre a pelve, empurre o quadril até ficar paralelo ao solo.',
    default_sets: 4,
    default_min_reps: 8,
    default_max_reps: 12,
    default_rest_seconds: 90,
    is_active: 1
  },
  {
    id: 'EX_GLU_003',
    name: 'Hip thrust no Smith',
    muscle_group: 'Glúteos',
    secondary_muscles: 'Posterior',
    equipment: 'Máquina Smith',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Barra guiada facilita estabilização e controle na subida.',
    instructions: 'Posicione o banco alinhado à barra guiada e execute a elevação completa.',
    default_sets: 4,
    default_min_reps: 10,
    default_max_reps: 12,
    default_rest_seconds: 75,
    is_active: 1
  },
  {
    id: 'EX_GLU_004',
    name: 'Hip thrust unilateral',
    muscle_group: 'Glúteos',
    secondary_muscles: 'Core, Isquiotibiais',
    equipment: 'Banco / Halter',
    exercise_type: 'Hipertrofia',
    difficulty: 'Intermediário',
    description: 'Trabalho focado em uma perna para ativação profunda e alinhamento do quadril.',
    instructions: 'Eleve o quadril usando apenas um pé, mantendo o outro joelho flexionado no ar.',
    default_sets: 3,
    default_min_reps: 10,
    default_max_reps: 15,
    default_rest_seconds: 45,
    is_active: 1
  },
  {
    id: 'EX_GLU_005',
    name: 'Glute bridge',
    muscle_group: 'Glúteos',
    secondary_muscles: 'Posterior',
    equipment: 'Peso Corporal',
    exercise_type: 'Ativação/Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Ponte de glúteos no solo para ativação neural e resistência.',
    instructions: 'Eleve o quadril mantendo o abdômen travado e segure 2 segundos no topo.',
    default_sets: 3,
    default_min_reps: 15,
    default_max_reps: 20,
    default_rest_seconds: 45,
    is_active: 1
  },
  {
    id: 'EX_GLU_006',
    name: 'Glute bridge unilateral',
    muscle_group: 'Glúteos',
    secondary_muscles: 'Core',
    equipment: 'Peso Corporal',
    exercise_type: 'Ativação',
    difficulty: 'Iniciante',
    description: 'Ponte unilateral com foco na estabilização do glúteo médio.',
    instructions: 'Suba o quadril com uma perna só sem deixar a pelve girar.',
    default_sets: 3,
    default_min_reps: 12,
    default_max_reps: 15,
    default_rest_seconds: 45,
    is_active: 1
  },
  {
    id: 'EX_GLU_007',
    name: 'Coice na polia',
    muscle_group: 'Glúteos',
    secondary_muscles: 'Posterior',
    equipment: 'Polia / Tornozeleira',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Extensão de quadril isolando o glúteo maior com tensão constante.',
    instructions: 'Com a tornozeleira presa, chute para trás estendendo o quadril sem hiperestender a lombar.',
    default_sets: 3,
    default_min_reps: 12,
    default_max_reps: 15,
    default_rest_seconds: 45,
    is_active: 1
  },
  {
    id: 'EX_GLU_008',
    name: 'Coice na máquina',
    muscle_group: 'Glúteos',
    secondary_muscles: 'Posterior',
    equipment: 'Máquina Glúteo',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Chute para trás guiado na máquina de glúteo.',
    instructions: 'Apoie o pé na plataforma e empurre para trás e para cima.',
    default_sets: 3,
    default_min_reps: 10,
    default_max_reps: 15,
    default_rest_seconds: 45,
    is_active: 1
  },
  {
    id: 'EX_GLU_009',
    name: 'Abdução na máquina',
    muscle_group: 'Glúteos',
    secondary_muscles: 'Glúteo médio, Glúteo mínimo',
    equipment: 'Cadeira Abdutora',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Foco no glúteo médio para preenchimento lateral do quadril.',
    instructions: 'Sente-se, abra as pernas contra as almofadas e segure a contração por 1 segundo.',
    default_sets: 4,
    default_min_reps: 12,
    default_max_reps: 20,
    default_rest_seconds: 45,
    is_active: 1
  },
  {
    id: 'EX_GLU_010',
    name: 'Abdução na polia',
    muscle_group: 'Glúteos',
    secondary_muscles: 'Glúteo médio',
    equipment: 'Polia / Tornozeleira',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Abdução em pé com cabo na polia baixa.',
    instructions: 'Com apoio lateral, afaste a perna lateralmente controlando o retorno.',
    default_sets: 3,
    default_min_reps: 12,
    default_max_reps: 15,
    default_rest_seconds: 45,
    is_active: 1
  },
  {
    id: 'EX_GLU_011',
    name: 'Abdução com miniband',
    muscle_group: 'Glúteos',
    secondary_muscles: 'Glúteo médio',
    equipment: 'Elástico Miniband',
    exercise_type: 'Ativação/Resistência',
    difficulty: 'Iniciante',
    description: 'Ativação pré-treino ou finalizador para queimação profunda.',
    instructions: 'Coloque a faixa acima dos joelhos e faça passos laterais ou abdução sentado.',
    default_sets: 3,
    default_min_reps: 15,
    default_max_reps: 25,
    default_rest_seconds: 30,
    is_active: 1
  },
  {
    id: 'EX_GLU_012',
    name: 'Agachamento sumô com halter',
    muscle_group: 'Glúteos',
    secondary_muscles: 'Adutores, Quadríceps',
    equipment: 'Halter / Steps',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Em cima de steps com halter pesado pendendo entre as pernas.',
    instructions: 'Desça profundo aproveitando a amplitude extra e suba espremendo os glúteos.',
    default_sets: 3,
    default_min_reps: 10,
    default_max_reps: 12,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_GLU_013',
    name: 'Afundo búlgaro',
    muscle_group: 'Glúteos',
    secondary_muscles: 'Quadríceps',
    equipment: 'Halteres / Banco',
    exercise_type: 'Hipertrofia',
    difficulty: 'Intermediário',
    description: 'Tronco levemente inclinado para frente aumenta a ênfase no glúteo da perna dianteira.',
    instructions: 'Incline o tronco a 30 graus e desça sentindo o alongamento do glúteo.',
    default_sets: 3,
    default_min_reps: 10,
    default_max_reps: 12,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_GLU_014',
    name: 'Levantamento terra sumô',
    muscle_group: 'Glúteos',
    secondary_muscles: 'Quadríceps, Adutores, Lombar',
    equipment: 'Barra',
    exercise_type: 'Força/Hipertrofia',
    difficulty: 'Avançado',
    description: 'Base ampla com tronco mais ereto enfatizando glúteos e pernas.',
    instructions: 'Pés bem abertos, mãos por dentro das pernas, empurre o chão estendendo quadril e joelhos juntos.',
    default_sets: 4,
    default_min_reps: 5,
    default_max_reps: 8,
    default_rest_seconds: 120,
    is_active: 1
  },

  // ================= Posterior de Coxa =================
  {
    id: 'EX_POS_001',
    name: 'Stiff com barra',
    muscle_group: 'Posterior de coxa',
    secondary_muscles: 'Glúteos, Lombar',
    equipment: 'Barra',
    exercise_type: 'Força/Hipertrofia',
    difficulty: 'Intermediário',
    description: 'Alongamento sob tensão de toda a cadeia posterior.',
    instructions: 'Pernas semiflexionadas e fixas, empurre o bumbum para trás descendo a barra rente às pernas.',
    default_sets: 4,
    default_min_reps: 8,
    default_max_reps: 12,
    default_rest_seconds: 90,
    is_active: 1
  },
  {
    id: 'EX_POS_002',
    name: 'Stiff com halteres',
    muscle_group: 'Posterior de coxa',
    secondary_muscles: 'Glúteos, Lombar',
    equipment: 'Halteres',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Permite rotação natural dos punhos e alinhamento biomecânico suave.',
    instructions: 'Desça os halteres rentes às canelas mantendo a coluna 100% reta.',
    default_sets: 3,
    default_min_reps: 10,
    default_max_reps: 12,
    default_rest_seconds: 75,
    is_active: 1
  },
  {
    id: 'EX_POS_003',
    name: 'Stiff unilateral',
    muscle_group: 'Posterior de coxa',
    secondary_muscles: 'Glúteos, Equilíbrio',
    equipment: 'Halteres',
    exercise_type: 'Hipertrofia/Funcional',
    difficulty: 'Intermediário',
    description: 'Trabalho de uma perna só, corrigindo fraquezas e estabilidade de tornozelo.',
    instructions: 'Equilibre-se em uma perna e estenda a outra para trás alinhada ao tronco.',
    default_sets: 3,
    default_min_reps: 8,
    default_max_reps: 12,
    default_rest_seconds: 45,
    is_active: 1
  },
  {
    id: 'EX_POS_004',
    name: 'Levantamento terra romeno',
    muscle_group: 'Posterior de coxa',
    secondary_muscles: 'Glúteos, Dorsal, Trapézio',
    equipment: 'Barra',
    exercise_type: 'Força/Hipertrofia',
    difficulty: 'Intermediário',
    description: 'RDL com foco na transição do quadril sem tocar a barra no chão.',
    instructions: 'Inicie do topo, desça até logo abaixo dos joelhos e suba com força dos isquiotibiais.',
    default_sets: 4,
    default_min_reps: 6,
    default_max_reps: 10,
    default_rest_seconds: 90,
    is_active: 1
  },
  {
    id: 'EX_POS_005',
    name: 'Terra romeno unilateral',
    muscle_group: 'Posterior de coxa',
    secondary_muscles: 'Glúteos, Core',
    equipment: 'Halter',
    exercise_type: 'Hipertrofia',
    difficulty: 'Intermediário',
    description: 'RDL unilateral com halter cruzado ou ipsilateral.',
    instructions: 'Desça o halter na direção do pé de apoio mantendo a pelve nivelada.',
    default_sets: 3,
    default_min_reps: 8,
    default_max_reps: 12,
    default_rest_seconds: 45,
    is_active: 1
  },
  {
    id: 'EX_POS_006',
    name: 'Mesa flexora',
    muscle_group: 'Posterior de coxa',
    secondary_muscles: 'Gastrocnêmio',
    equipment: 'Máquina Mesa Flexora',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Flexão de joelhos deitado, trabalhando o bíceps femoral em extensão de quadril.',
    instructions: 'Deitado de bruços, flexione as pernas trazendo o rolo até encostar nos glúteos.',
    default_sets: 4,
    default_min_reps: 10,
    default_max_reps: 12,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_POS_007',
    name: 'Mesa flexora unilateral',
    muscle_group: 'Posterior de coxa',
    secondary_muscles: 'Gastrocnêmio',
    equipment: 'Máquina',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Mesa flexora com uma perna de cada vez.',
    instructions: 'Isole o movimento em cada perna mantendo o quadril colado no banco.',
    default_sets: 3,
    default_min_reps: 10,
    default_max_reps: 12,
    default_rest_seconds: 45,
    is_active: 1
  },
  {
    id: 'EX_POS_008',
    name: 'Cadeira flexora',
    muscle_group: 'Posterior de coxa',
    secondary_muscles: 'Gastrocnêmio',
    equipment: 'Máquina Cadeira Flexora',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Quadril flexionado alonga a origem dos isquiotibiais para hipertrofia superior.',
    instructions: 'Trave a almofada sobre as coxas e flexione os joelhos para baixo com força.',
    default_sets: 4,
    default_min_reps: 10,
    default_max_reps: 15,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_POS_009',
    name: 'Flexora em pé',
    muscle_group: 'Posterior de coxa',
    secondary_muscles: 'Panturrilha',
    equipment: 'Máquina Flexora em Pé',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Flexão unilateral em pé com apoio da coxa.',
    instructions: 'Flexione a perna para cima até o calcanhar se aproximar do glúteo.',
    default_sets: 3,
    default_min_reps: 10,
    default_max_reps: 12,
    default_rest_seconds: 45,
    is_active: 1
  },
  {
    id: 'EX_POS_010',
    name: 'Flexora unilateral em pé',
    muscle_group: 'Posterior de coxa',
    secondary_muscles: 'Panturrilha',
    equipment: 'Máquina / Polia',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Isolamento individual com cabo ou alavanca.',
    instructions: 'Suba o rolo com controle e desça sem deixar o peso bater.',
    default_sets: 3,
    default_min_reps: 12,
    default_max_reps: 15,
    default_rest_seconds: 45,
    is_active: 1
  },
  {
    id: 'EX_POS_011',
    name: 'Flexão nórdica',
    muscle_group: 'Posterior de coxa',
    secondary_muscles: 'Glúteos, Core',
    equipment: 'Banco Nórdico / Apoio Pés',
    exercise_type: 'Força Excêntrica',
    difficulty: 'Avançado',
    description: 'O melhor exercício para prevenção de lesões e força excêntrica dos isquiotibiais.',
    instructions: 'Com tornozelos travados, desça o tronco lentamente para frente resistindo à gravidade.',
    default_sets: 3,
    default_min_reps: 5,
    default_max_reps: 8,
    default_rest_seconds: 90,
    is_active: 1
  },
  {
    id: 'EX_POS_012',
    name: 'Nordic curl',
    muscle_group: 'Posterior de coxa',
    secondary_muscles: 'Core',
    equipment: 'Apoio de Tornozelo',
    exercise_type: 'Força',
    difficulty: 'Avançado',
    description: 'Versão avançada com contração de retorno.',
    instructions: 'Controle a descida e empurre suavemente para voltar à vertical.',
    default_sets: 3,
    default_min_reps: 4,
    default_max_reps: 8,
    default_rest_seconds: 90,
    is_active: 1
  },
  {
    id: 'EX_POS_013',
    name: 'Good morning',
    muscle_group: 'Posterior de coxa',
    secondary_muscles: 'Glúteos, Eretores da Espinha',
    equipment: 'Barra',
    exercise_type: 'Hipertrofia',
    difficulty: 'Intermediário',
    description: 'Barra sobre as costas, flexão do quadril com joelhos quase retos.',
    instructions: 'Curve o quadril à frente mantendo a coluna em arco neutro.',
    default_sets: 3,
    default_min_reps: 8,
    default_max_reps: 12,
    default_rest_seconds: 75,
    is_active: 1
  },
  {
    id: 'EX_POS_014',
    name: 'Good morning no Smith',
    muscle_group: 'Posterior de coxa',
    secondary_muscles: 'Lombar',
    equipment: 'Máquina Smith',
    exercise_type: 'Hipertrofia',
    difficulty: 'Intermediário',
    description: 'Trajetória guiada proporcionando mais estabilidade.',
    instructions: 'Incline o tronco para frente sentindo posterior de coxa esticar.',
    default_sets: 3,
    default_min_reps: 10,
    default_max_reps: 12,
    default_rest_seconds: 60,
    is_active: 1
  },

  // ================= Panturrilha =================
  {
    id: 'EX_PAN_001',
    name: 'Panturrilha em pé',
    muscle_group: 'Panturrilha',
    secondary_muscles: 'Gastrocnêmio',
    equipment: 'Máquina / Step',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Joelho estendido enfatiza o gastrocnêmio para volume e definição.',
    instructions: 'Ponta dos pés no degrau, desça o calcanhar alongando ao máximo e suba ficando na ponta dos pés.',
    default_sets: 4,
    default_min_reps: 12,
    default_max_reps: 15,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_PAN_002',
    name: 'Panturrilha sentado',
    muscle_group: 'Panturrilha',
    secondary_muscles: 'Sóleo',
    equipment: 'Máquina Panturrilha Sentado',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Joelhos a 90 graus isolam o músculo sóleo dando largura à panturrilha.',
    instructions: 'Apoio sobre as coxas, eleve os calcanhares e segure 2 segundos no topo.',
    default_sets: 4,
    default_min_reps: 15,
    default_max_reps: 20,
    default_rest_seconds: 45,
    is_active: 1
  },
  {
    id: 'EX_PAN_003',
    name: 'Panturrilha no Smith',
    muscle_group: 'Panturrilha',
    secondary_muscles: 'Gastrocnêmio',
    equipment: 'Máquina Smith / Step',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Barra do Smith apoiada nos ombros sobre um degrau.',
    instructions: 'Execute a flexão plantar completa com segurança da barra guiada.',
    default_sets: 4,
    default_min_reps: 12,
    default_max_reps: 15,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_PAN_004',
    name: 'Panturrilha no leg press',
    muscle_group: 'Panturrilha',
    secondary_muscles: 'Gastrocnêmio',
    equipment: 'Máquina Leg Press',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Ponta dos pés na borda inferior da plataforma do Leg.',
    instructions: 'Com joelhos destravados, empurre a plataforma apenas com os tornozelos.',
    default_sets: 4,
    default_min_reps: 12,
    default_max_reps: 15,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_PAN_005',
    name: 'Panturrilha unilateral',
    muscle_group: 'Panturrilha',
    secondary_muscles: 'Sóleo, Gastrocnêmio',
    equipment: 'Step / Halter',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Excelente para sobrecarga sem precisar de pesos gigantes.',
    instructions: 'Em um pé só no degrau, faça a amplitude máxima de subida e descida.',
    default_sets: 3,
    default_min_reps: 12,
    default_max_reps: 15,
    default_rest_seconds: 45,
    is_active: 1
  },
  {
    id: 'EX_PAN_006',
    name: 'Panturrilha unilateral em pé',
    muscle_group: 'Panturrilha',
    secondary_muscles: 'Gastrocnêmio',
    equipment: 'Peso Corporal / Halter',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Segurando um halter em uma mão e apoiando a outra para equilíbrio.',
    instructions: 'Suba o máximo na ponta do pé e desça sentindo o tendão alongar.',
    default_sets: 3,
    default_min_reps: 12,
    default_max_reps: 15,
    default_rest_seconds: 45,
    is_active: 1
  },
  {
    id: 'EX_PAN_007',
    name: 'Panturrilha no hack',
    muscle_group: 'Panturrilha',
    secondary_muscles: 'Gastrocnêmio',
    equipment: 'Máquina Hack',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Pontas dos pés na borda da plataforma do Hack.',
    instructions: 'Empurre a almofada dos ombros flexionando os pés.',
    default_sets: 3,
    default_min_reps: 12,
    default_max_reps: 15,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_PAN_008',
    name: 'Donkey calf raise',
    muscle_group: 'Panturrilha',
    secondary_muscles: 'Gastrocnêmio',
    equipment: 'Máquina Burrinho / Parceiro',
    exercise_type: 'Hipertrofia',
    difficulty: 'Intermediário',
    description: 'Tronco a 90 graus coloca o gastrocnêmio em máximo estiramento passivo.',
    instructions: 'Incline o tronco, apoie o peso sobre o quadril e faça a elevação.',
    default_sets: 4,
    default_min_reps: 15,
    default_max_reps: 20,
    default_rest_seconds: 60,
    is_active: 1
  },

  // ================= Ombros =================
  {
    id: 'EX_OMB_001',
    name: 'Desenvolvimento com barra',
    muscle_group: 'Ombros',
    secondary_muscles: 'Tríceps, Trapézio',
    equipment: 'Barra',
    exercise_type: 'Força/Hipertrofia',
    difficulty: 'Intermediário',
    description: 'Military press clássico para força e largura escapular.',
    instructions: 'Barra na altura da clavícula, empurre acima da cabeça até estender os braços.',
    default_sets: 4,
    default_min_reps: 6,
    default_max_reps: 10,
    default_rest_seconds: 90,
    is_active: 1
  },
  {
    id: 'EX_OMB_002',
    name: 'Desenvolvimento com halteres',
    muscle_group: 'Ombros',
    secondary_muscles: 'Tríceps',
    equipment: 'Halteres / Banco',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Permite trajetória convergente e estabilidade articular.',
    instructions: 'Banco a 80 graus, empurre os halteres para cima aproximando-os no topo.',
    default_sets: 4,
    default_min_reps: 8,
    default_max_reps: 12,
    default_rest_seconds: 75,
    is_active: 1
  },
  {
    id: 'EX_OMB_003',
    name: 'Desenvolvimento Arnold',
    muscle_group: 'Ombros',
    secondary_muscles: 'Deltoide lateral, Tríceps',
    equipment: 'Halteres',
    exercise_type: 'Hipertrofia',
    difficulty: 'Intermediário',
    description: 'Inicia com pegada supinada e roda os braços durante a subida.',
    instructions: 'Halteres na frente do peito com palmas para dentro, gire e empurre para cima.',
    default_sets: 3,
    default_min_reps: 8,
    default_max_reps: 12,
    default_rest_seconds: 75,
    is_active: 1
  },
  {
    id: 'EX_OMB_004',
    name: 'Desenvolvimento na máquina',
    muscle_group: 'Ombros',
    secondary_muscles: 'Tríceps',
    equipment: 'Máquina',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Trajetória guiada com segurança para alcançar a falha muscular.',
    instructions: 'Ajuste o assento e empurre as manoplas verticalmente.',
    default_sets: 3,
    default_min_reps: 10,
    default_max_reps: 12,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_OMB_005',
    name: 'Desenvolvimento unilateral',
    muscle_group: 'Ombros',
    secondary_muscles: 'Core, Tríceps',
    equipment: 'Halter / Kettlebell',
    exercise_type: 'Hipertrofia/Funcional',
    difficulty: 'Intermediário',
    description: 'Foco unilateral com grande ativação dos estabilizadores do core.',
    instructions: 'Empurre com um braço mantendo o tronco ereto sem inclinar para o lado.',
    default_sets: 3,
    default_min_reps: 8,
    default_max_reps: 12,
    default_rest_seconds: 45,
    is_active: 1
  },
  {
    id: 'EX_OMB_006',
    name: 'Elevação lateral com halteres',
    muscle_group: 'Ombros',
    secondary_muscles: 'Trapézio',
    equipment: 'Halteres',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'O exercício definitivo para o aspecto de ombros largos (deltoide lateral).',
    instructions: 'Eleve os halteres lateralmente até a linha dos ombros, cotovelos levemente flexionados.',
    default_sets: 4,
    default_min_reps: 12,
    default_max_reps: 15,
    default_rest_seconds: 45,
    is_active: 1
  },
  {
    id: 'EX_OMB_007',
    name: 'Elevação lateral na polia',
    muscle_group: 'Ombros',
    secondary_muscles: 'Trapézio',
    equipment: 'Polia',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Cabo garante tensão mecânica desde o primeiro centímetro de movimento.',
    instructions: 'Cabo cruzando por trás ou pela frente, puxe lateralmente até a altura do ombro.',
    default_sets: 3,
    default_min_reps: 12,
    default_max_reps: 15,
    default_rest_seconds: 45,
    is_active: 1
  },
  {
    id: 'EX_OMB_008',
    name: 'Elevação lateral unilateral',
    muscle_group: 'Ombros',
    secondary_muscles: 'Deltoide lateral',
    equipment: 'Halter / Polia',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Foco total no deltoide lateral de cada lado.',
    instructions: 'Incline ligeiramente o tronco e eleve o peso lateralmente sem balanço.',
    default_sets: 3,
    default_min_reps: 12,
    default_max_reps: 15,
    default_rest_seconds: 45,
    is_active: 1
  },
  {
    id: 'EX_OMB_009',
    name: 'Elevação lateral na máquina',
    muscle_group: 'Ombros',
    secondary_muscles: 'Deltoide lateral',
    equipment: 'Máquina',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Alavancas nos antebraços eliminam a fadiga de pegada.',
    instructions: 'Apoie os braços nas almofadas e faça a abdução lateral controlando a volta.',
    default_sets: 3,
    default_min_reps: 12,
    default_max_reps: 15,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_OMB_010',
    name: 'Elevação frontal com halteres',
    muscle_group: 'Ombros',
    secondary_muscles: 'Peito superior',
    equipment: 'Halteres',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Isola o deltoide anterior.',
    instructions: 'Eleve os halteres à frente do corpo até a linha dos olhos.',
    default_sets: 3,
    default_min_reps: 10,
    default_max_reps: 12,
    default_rest_seconds: 45,
    is_active: 1
  },
  {
    id: 'EX_OMB_011',
    name: 'Elevação frontal com barra',
    muscle_group: 'Ombros',
    secondary_muscles: 'Peito superior',
    equipment: 'Barra',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Movimento bilateral com barra reta ou W.',
    instructions: 'Segure na largura dos ombros e levante a barra à frente sem balançar a coluna.',
    default_sets: 3,
    default_min_reps: 10,
    default_max_reps: 12,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_OMB_012',
    name: 'Elevação frontal na polia',
    muscle_group: 'Ombros',
    secondary_muscles: 'Peito superior',
    equipment: 'Polia',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Polia baixa passando por entre as pernas com barra ou corda.',
    instructions: 'Suba o cabo até a altura dos olhos e desça em 2 segundos.',
    default_sets: 3,
    default_min_reps: 12,
    default_max_reps: 15,
    default_rest_seconds: 45,
    is_active: 1
  },
  {
    id: 'EX_OMB_013',
    name: 'Crucifixo inverso',
    muscle_group: 'Ombros',
    secondary_muscles: 'Trapézio médio, Romboides',
    equipment: 'Halteres / Banco',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Tronco inclinado, abre os braços para ativar o deltoide posterior.',
    instructions: 'Incline o tronco para frente e abra os braços em arco apertando as costas.',
    default_sets: 3,
    default_min_reps: 12,
    default_max_reps: 15,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_OMB_014',
    name: 'Crucifixo inverso na máquina',
    muscle_group: 'Ombros',
    secondary_muscles: 'Romboides',
    equipment: 'Máquina Peck Deck Inverso',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Peito apoiado no encosto para isolamento do deltoide posterior.',
    instructions: 'Segure as manoplas e abra os braços para trás com controle.',
    default_sets: 4,
    default_min_reps: 12,
    default_max_reps: 15,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_OMB_015',
    name: 'Crucifixo inverso na polia',
    muscle_group: 'Ombros',
    secondary_muscles: 'Trapézio',
    equipment: 'Polia Dupla',
    exercise_type: 'Hipertrofia',
    difficulty: 'Intermediário',
    description: 'Cabos cruzados na altura dos ombros.',
    instructions: 'Puxe os cabos abrindo os braços para trás e para fora.',
    default_sets: 3,
    default_min_reps: 12,
    default_max_reps: 15,
    default_rest_seconds: 45,
    is_active: 1
  },
  {
    id: 'EX_OMB_016',
    name: 'Face pull',
    muscle_group: 'Ombros',
    secondary_muscles: 'Trapézio, Manguito Rotador',
    equipment: 'Polia / Corda',
    exercise_type: 'Hipertrofia/Postura',
    difficulty: 'Iniciante',
    description: 'Exercício essencial para saúde dos ombros e postura.',
    instructions: 'Puxe a corda em direção ao rosto abrindo as mãos e rodando os ombros para fora.',
    default_sets: 4,
    default_min_reps: 12,
    default_max_reps: 15,
    default_rest_seconds: 45,
    is_active: 1
  },
  {
    id: 'EX_OMB_017',
    name: 'Remada alta',
    muscle_group: 'Ombros',
    secondary_muscles: 'Trapézio',
    equipment: 'Barra / Halteres',
    exercise_type: 'Hipertrofia',
    difficulty: 'Intermediário',
    description: 'Pegada na largura dos ombros puxando para cima.',
    instructions: 'Puxe a barra até a altura do peito mantendo os cotovelos sempre mais altos que os punhos.',
    default_sets: 3,
    default_min_reps: 10,
    default_max_reps: 12,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_OMB_018',
    name: 'Remada alta na polia',
    muscle_group: 'Ombros',
    secondary_muscles: 'Trapézio',
    equipment: 'Polia',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Remada vertical com cabo na polia baixa.',
    instructions: 'Puxe a barra para cima guiada pelo cabo, cotovelos apontados para o teto.',
    default_sets: 3,
    default_min_reps: 10,
    default_max_reps: 12,
    default_rest_seconds: 60,
    is_active: 1
  },

  // ================= Trapézio =================
  {
    id: 'EX_TRP_001',
    name: 'Encolhimento com barra',
    muscle_group: 'Trapézio',
    secondary_muscles: 'Antebraço',
    equipment: 'Barra',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Elevação pura das escápulas construindo o trapézio superior.',
    instructions: 'Segure a barra e encolha os ombros na direção das orelhas sem girar.',
    default_sets: 4,
    default_min_reps: 10,
    default_max_reps: 15,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_TRP_002',
    name: 'Encolhimento com halteres',
    muscle_group: 'Trapézio',
    secondary_muscles: 'Antebraço',
    equipment: 'Halteres',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Halteres ao lado do corpo permitem um alinhamento neutro mais anatômico.',
    instructions: 'Suba os ombros verticalmente e segure 1 segundo no pico de contração.',
    default_sets: 4,
    default_min_reps: 10,
    default_max_reps: 15,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_TRP_003',
    name: 'Encolhimento no Smith',
    muscle_group: 'Trapézio',
    secondary_muscles: 'Antebraço',
    equipment: 'Máquina Smith',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Barra guiada pela frente ou por trás das coxas.',
    instructions: 'Encolha os ombros mantendo os braços completamente estendidos.',
    default_sets: 3,
    default_min_reps: 12,
    default_max_reps: 15,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_TRP_004',
    name: 'Encolhimento na máquina',
    muscle_group: 'Trapézio',
    secondary_muscles: 'Antebraço',
    equipment: 'Máquina',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Máquina específica de encolhimento ou no aparelho de panturrilha em pé.',
    instructions: 'Eleve as almofadas ou manoplas estritamente com os trapézios.',
    default_sets: 3,
    default_min_reps: 12,
    default_max_reps: 15,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_TRP_005',
    name: 'Encolhimento na polia',
    muscle_group: 'Trapézio',
    secondary_muscles: 'Antebraço',
    equipment: 'Polia',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Tensão diagonal contínua puxando para baixo e para fora.',
    instructions: 'Segure as manoplas na polia baixa e eleve os ombros.',
    default_sets: 3,
    default_min_reps: 12,
    default_max_reps: 15,
    default_rest_seconds: 45,
    is_active: 1
  },
  {
    id: 'EX_TRP_006',
    name: 'Encolhimento unilateral',
    muscle_group: 'Trapézio',
    secondary_muscles: 'Antebraço',
    equipment: 'Halter / Polia',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Foco em um lado para máxima elevação escapular.',
    instructions: 'Encolha um ombro de cada vez com total amplitude.',
    default_sets: 3,
    default_min_reps: 12,
    default_max_reps: 15,
    default_rest_seconds: 45,
    is_active: 1
  },
  {
    id: 'EX_TRP_007',
    name: 'Farmer\'s walk',
    muscle_group: 'Trapézio',
    secondary_muscles: 'Antebraço, Core, Pernas',
    equipment: 'Halteres / Trap Bar',
    exercise_type: 'Força/Resistência',
    difficulty: 'Intermediário',
    description: 'Caminhada segurando cargas pesadas nas mãos.',
    instructions: 'Postura ereta, caminhe a passos curtos e firmes sem deixar os ombros caírem.',
    default_sets: 4,
    default_min_reps: 30,
    default_max_reps: 60,
    default_rest_seconds: 90,
    is_active: 1
  },
  {
    id: 'EX_TRP_008',
    name: 'High pull',
    muscle_group: 'Trapézio',
    secondary_muscles: 'Ombros, Pernas',
    equipment: 'Barra',
    exercise_type: 'Potência/Força',
    difficulty: 'Avançado',
    description: 'Puxada explosiva tripla extensão para trapézio e potência.',
    instructions: 'Impulsione com o quadril e puxe a barra até o peito alto.',
    default_sets: 4,
    default_min_reps: 5,
    default_max_reps: 8,
    default_rest_seconds: 90,
    is_active: 1
  },

  // ================= Abdômen =================
  {
    id: 'EX_ABD_001',
    name: 'Abdominal tradicional',
    muscle_group: 'Abdômen',
    secondary_muscles: 'Reto abdominal',
    equipment: 'Solo / Colchonete',
    exercise_type: 'Resistência/Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Flexão do tronco no solo.',
    instructions: 'Mãos na cabeça sem puxar o pescoço, flexione o tronco aproximando as costelas do quadril.',
    default_sets: 3,
    default_min_reps: 15,
    default_max_reps: 20,
    default_rest_seconds: 45,
    is_active: 1
  },
  {
    id: 'EX_ABD_002',
    name: 'Abdominal supra',
    muscle_group: 'Abdômen',
    secondary_muscles: 'Reto abdominal superior',
    equipment: 'Colchonete',
    exercise_type: 'Resistência',
    difficulty: 'Iniciante',
    description: 'Foco na porção superior do reto abdominal.',
    instructions: 'Curvando a parte superior das costas para cima soltando todo o ar.',
    default_sets: 3,
    default_min_reps: 15,
    default_max_reps: 25,
    default_rest_seconds: 45,
    is_active: 1
  },
  {
    id: 'EX_ABD_003',
    name: 'Abdominal infra',
    muscle_group: 'Abdômen',
    secondary_muscles: 'Flexores de quadril',
    equipment: 'Colchonete / Solo',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Elevação da pelve em direção ao tronco.',
    instructions: 'Deitado, levante as pernas e descole o quadril do solo no final.',
    default_sets: 3,
    default_min_reps: 12,
    default_max_reps: 15,
    default_rest_seconds: 45,
    is_active: 1
  },
  {
    id: 'EX_ABD_004',
    name: 'Elevação de pernas',
    muscle_group: 'Abdômen',
    secondary_muscles: 'Iliopsoas',
    equipment: 'Banco / Solo',
    exercise_type: 'Resistência',
    difficulty: 'Iniciante',
    description: 'Subida e descida controlada das pernas estendidas.',
    instructions: 'Desça as pernas sem arquear a lombar e suba contraindo o abdômen.',
    default_sets: 3,
    default_min_reps: 12,
    default_max_reps: 15,
    default_rest_seconds: 45,
    is_active: 1
  },
  {
    id: 'EX_ABD_005',
    name: 'Elevação de joelhos',
    muscle_group: 'Abdômen',
    secondary_muscles: 'Flexores de quadril',
    equipment: 'Paralelas / Solo',
    exercise_type: 'Resistência',
    difficulty: 'Iniciante',
    description: 'Puxada dos joelhos até o peito.',
    instructions: 'Suba os joelhos dobrados enrolando a pelve.',
    default_sets: 3,
    default_min_reps: 12,
    default_max_reps: 20,
    default_rest_seconds: 45,
    is_active: 1
  },
  {
    id: 'EX_ABD_006',
    name: 'Elevação de pernas na barra fixa',
    muscle_group: 'Abdômen',
    secondary_muscles: 'Antebraço, Flexores',
    equipment: 'Barra Fixa',
    exercise_type: 'Força/Hipertrofia',
    difficulty: 'Avançado',
    description: 'Toes to bar ou pernas a 90 graus suspenso na barra.',
    instructions: 'Pendurado, eleve as pernas estendidas sem balançar o corpo.',
    default_sets: 3,
    default_min_reps: 8,
    default_max_reps: 12,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_ABD_007',
    name: 'Abdominal na máquina',
    muscle_group: 'Abdômen',
    secondary_muscles: 'Reto abdominal',
    equipment: 'Máquina',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Permite sobrecarga progressiva com placas de peso.',
    instructions: 'Ajuste o peso e flexione o tronco para frente soltando o ar.',
    default_sets: 3,
    default_min_reps: 10,
    default_max_reps: 15,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_ABD_008',
    name: 'Abdominal na polia',
    muscle_group: 'Abdômen',
    secondary_muscles: 'Reto abdominal',
    equipment: 'Polia / Corda',
    exercise_type: 'Hipertrofia',
    difficulty: 'Intermediário',
    description: 'Abdominal ajoelhado no pulley alto.',
    instructions: 'Ajoelhado, segure a corda junto à cabeça e curve a coluna aproximando a testa dos joelhos.',
    default_sets: 3,
    default_min_reps: 12,
    default_max_reps: 15,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_ABD_009',
    name: 'Abdominal com peso',
    muscle_group: 'Abdômen',
    secondary_muscles: 'Reto abdominal',
    equipment: 'Anilha / Halter',
    exercise_type: 'Hipertrofia',
    difficulty: 'Intermediário',
    description: 'Segurando uma anilha no peito ou braços estendidos.',
    instructions: 'Execute a flexão abdominal com sobrecarga adicional.',
    default_sets: 3,
    default_min_reps: 10,
    default_max_reps: 12,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_ABD_010',
    name: 'Abdominal bicicleta',
    muscle_group: 'Abdômen',
    secondary_muscles: 'Oblíquos',
    equipment: 'Colchonete',
    exercise_type: 'Resistência',
    difficulty: 'Iniciante',
    description: 'Cruza cotovelo com joelho oposto com movimento contínuo.',
    instructions: 'Pedale com as pernas enquanto gira o tronco trazendo o cotovelo ao joelho oposto.',
    default_sets: 3,
    default_min_reps: 15,
    default_max_reps: 25,
    default_rest_seconds: 45,
    is_active: 1
  },
  {
    id: 'EX_ABD_011',
    name: 'Abdominal canivete',
    muscle_group: 'Abdômen',
    secondary_muscles: 'Flexores de quadril',
    equipment: 'Colchonete',
    exercise_type: 'Força/Resistência',
    difficulty: 'Intermediário',
    description: 'Fechamento simultâneo de pernas e tronco.',
    instructions: 'Suba pernas e braços estendidos encontrando as mãos nos pés.',
    default_sets: 3,
    default_min_reps: 10,
    default_max_reps: 15,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_ABD_012',
    name: 'Abdominal V-up',
    muscle_group: 'Abdômen',
    secondary_muscles: 'Core',
    equipment: 'Colchonete',
    exercise_type: 'Força',
    difficulty: 'Intermediário',
    description: 'Forma de V entre tronco e pernas equilibrando sobre os glúteos.',
    instructions: 'Suba explosivo e controle a descida sem encostar os pés no chão.',
    default_sets: 3,
    default_min_reps: 8,
    default_max_reps: 12,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_ABD_013',
    name: 'Abdominal reverso',
    muscle_group: 'Abdômen',
    secondary_muscles: 'Infra',
    equipment: 'Banco / Colchonete',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Descola o quadril enrolando a coluna lombar.',
    instructions: 'Puxe os joelhos em direção à cabeça tirando a pelve do solo.',
    default_sets: 3,
    default_min_reps: 12,
    default_max_reps: 15,
    default_rest_seconds: 45,
    is_active: 1
  },
  {
    id: 'EX_ABD_014',
    name: 'Abdominal declinado',
    muscle_group: 'Abdômen',
    secondary_muscles: 'Reto abdominal',
    equipment: 'Banco Declinado',
    exercise_type: 'Hipertrofia',
    difficulty: 'Intermediário',
    description: 'Maior amplitude contra a gravidade no banco declinado.',
    instructions: 'Pés travados, desça o tronco até a linha do banco e suba enrolando.',
    default_sets: 3,
    default_min_reps: 12,
    default_max_reps: 15,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_ABD_015',
    name: 'Sit-up',
    muscle_group: 'Abdômen',
    secondary_muscles: 'Flexores de quadril',
    equipment: 'Colchonete',
    exercise_type: 'Resistência/Funcional',
    difficulty: 'Iniciante',
    description: 'Subida completa do tronco até a posição sentada.',
    instructions: 'Suba o tronco inteiro até sentar e retorne de forma suave.',
    default_sets: 3,
    default_min_reps: 15,
    default_max_reps: 20,
    default_rest_seconds: 45,
    is_active: 1
  },
  {
    id: 'EX_ABD_016',
    name: 'Crunch',
    muscle_group: 'Abdômen',
    secondary_muscles: 'Reto abdominal',
    equipment: 'Colchonete',
    exercise_type: 'Resistência',
    difficulty: 'Iniciante',
    description: 'Curvatura rápida das costas focando em queimação e controle.',
    instructions: 'Eleve apenas as escápulas espremendo o abdômen.',
    default_sets: 3,
    default_min_reps: 15,
    default_max_reps: 20,
    default_rest_seconds: 30,
    is_active: 1
  },
  {
    id: 'EX_ABD_017',
    name: 'Crunch na polia',
    muscle_group: 'Abdômen',
    secondary_muscles: 'Reto abdominal',
    equipment: 'Polia / Corda',
    exercise_type: 'Hipertrofia',
    difficulty: 'Intermediário',
    description: 'Trabalho de tensão contínua ajoelhado no cross.',
    instructions: 'Contraia o abdômen puxando a corda sem usar os braços.',
    default_sets: 3,
    default_min_reps: 12,
    default_max_reps: 15,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_ABD_018',
    name: 'Russian twist',
    muscle_group: 'Abdômen',
    secondary_muscles: 'Oblíquos',
    equipment: 'Anilha / Peso Corporal',
    exercise_type: 'Resistência/Rotacional',
    difficulty: 'Iniciante',
    description: 'Rotação do tronco sentado com pés elevados.',
    instructions: 'Gire o tronco de um lado para o outro tocando o peso no chão.',
    default_sets: 3,
    default_min_reps: 15,
    default_max_reps: 20,
    default_rest_seconds: 45,
    is_active: 1
  },
  {
    id: 'EX_ABD_019',
    name: 'Prancha',
    muscle_group: 'Abdômen',
    secondary_muscles: 'Transverso, Core',
    equipment: 'Colchonete',
    exercise_type: 'Isometria/Estabilidade',
    difficulty: 'Iniciante',
    description: 'Sustentação isométrica fortalecendo a cinta abdominal profunda.',
    instructions: 'Apoie os antebraços e pontas dos pés, mantendo o corpo em linha reta e abdômen apertado.',
    default_sets: 3,
    default_min_reps: 30,
    default_max_reps: 60,
    default_rest_seconds: 45,
    is_active: 1
  },
  {
    id: 'EX_ABD_020',
    name: 'Prancha lateral',
    muscle_group: 'Abdômen',
    secondary_muscles: 'Oblíquos, Glúteo médio',
    equipment: 'Colchonete',
    exercise_type: 'Isometria',
    difficulty: 'Iniciante',
    description: 'Isometria lateral fortalecendo oblíquos e coluna.',
    instructions: 'Apoie um antebraço de lado e eleve o quadril mantendo o alinhamento.',
    default_sets: 3,
    default_min_reps: 20,
    default_max_reps: 45,
    default_rest_seconds: 30,
    is_active: 1
  },
  {
    id: 'EX_ABD_021',
    name: 'Prancha com peso',
    muscle_group: 'Abdômen',
    secondary_muscles: 'Core',
    equipment: 'Anilha',
    exercise_type: 'Força Isométrica',
    difficulty: 'Avançado',
    description: 'Prancha com anilha pesada posicionada sobre a lombar/costas.',
    instructions: 'Mantenha a postura perfeitamente reta sem deixar o quadril cair.',
    default_sets: 3,
    default_min_reps: 30,
    default_max_reps: 45,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_ABD_022',
    name: 'Mountain climber',
    muscle_group: 'Abdômen',
    secondary_muscles: 'Cardio, Ombros',
    equipment: 'Peso Corporal',
    exercise_type: 'Dinâmico/Cardio',
    difficulty: 'Iniciante',
    description: 'Puxadas alternadas rápidas dos joelhos na posição de prancha.',
    instructions: 'Em posição de flexão, alterne os joelhos rapidamente em direção ao peito.',
    default_sets: 3,
    default_min_reps: 20,
    default_max_reps: 40,
    default_rest_seconds: 45,
    is_active: 1
  },
  {
    id: 'EX_ABD_023',
    name: 'Dead bug',
    muscle_group: 'Abdômen',
    secondary_muscles: 'Coordenação, Core',
    equipment: 'Colchonete',
    exercise_type: 'Estabilidade',
    difficulty: 'Iniciante',
    description: 'Extensão contra-lateral de braço e perna mantendo a lombar colada.',
    instructions: 'Deitado de costas, estenda o braço direito e a perna esquerda e alterne suavemente.',
    default_sets: 3,
    default_min_reps: 10,
    default_max_reps: 15,
    default_rest_seconds: 30,
    is_active: 1
  },
  {
    id: 'EX_ABD_024',
    name: 'Hollow body hold',
    muscle_group: 'Abdômen',
    secondary_muscles: 'Cadeia anterior',
    equipment: 'Colchonete',
    exercise_type: 'Isometria Ginástica',
    difficulty: 'Avançado',
    description: 'Posição de canoa ginástica com máxima retroversão pélvica.',
    instructions: 'Braços esticados atrás da cabeça, pernas esticadas à frente, curve o corpo como uma canoa.',
    default_sets: 3,
    default_min_reps: 20,
    default_max_reps: 40,
    default_rest_seconds: 60,
    is_active: 1
  },

  // ================= Antebraço =================
  {
    id: 'EX_ANT_001',
    name: 'Rosca de punho',
    muscle_group: 'Antebraço',
    secondary_muscles: 'Flexores de punho',
    equipment: 'Barra / Halteres',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Flexão dos punhos com antebraços apoiados nas coxas ou banco.',
    instructions: 'Palmas para cima, role o peso até as pontas dos dedos e suba flexionando o punho.',
    default_sets: 3,
    default_min_reps: 12,
    default_max_reps: 15,
    default_rest_seconds: 45,
    is_active: 1
  },
  {
    id: 'EX_ANT_002',
    name: 'Rosca de punho inversa',
    muscle_group: 'Antebraço',
    secondary_muscles: 'Extensores de punho',
    equipment: 'Barra / Halteres',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Extensão dos punhos com palmas voltadas para baixo.',
    instructions: 'Palmas para baixo, eleve os nós dos dedos em direção ao teto.',
    default_sets: 3,
    default_min_reps: 12,
    default_max_reps: 15,
    default_rest_seconds: 45,
    is_active: 1
  },
  {
    id: 'EX_ANT_003',
    name: 'Wrist curl com barra',
    muscle_group: 'Antebraço',
    secondary_muscles: 'Flexores',
    equipment: 'Barra',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Flexão de punhos com barra reta sentado no banco.',
    instructions: 'Execute a flexão estrita dos punhos com carga controlada.',
    default_sets: 3,
    default_min_reps: 12,
    default_max_reps: 15,
    default_rest_seconds: 45,
    is_active: 1
  },
  {
    id: 'EX_ANT_004',
    name: 'Wrist curl com halteres',
    muscle_group: 'Antebraço',
    secondary_muscles: 'Flexores',
    equipment: 'Halteres',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Maior liberdade para cada punho trabalhar de forma isolada.',
    instructions: 'Flexione os punhos para cima segurando os halteres com firmeza.',
    default_sets: 3,
    default_min_reps: 12,
    default_max_reps: 15,
    default_rest_seconds: 45,
    is_active: 1
  },
  {
    id: 'EX_ANT_005',
    name: 'Extensão de punho',
    muscle_group: 'Antebraço',
    secondary_muscles: 'Extensores',
    equipment: 'Halteres / Barra',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Fortalecimento da musculatura extensora do antebraço.',
    instructions: 'Suba o dorso da mão controlando a descida.',
    default_sets: 3,
    default_min_reps: 12,
    default_max_reps: 15,
    default_rest_seconds: 45,
    is_active: 1
  },
  {
    id: 'EX_ANT_006',
    name: 'Farmer\'s walk',
    muscle_group: 'Antebraço',
    secondary_muscles: 'Pegada, Trapézio',
    equipment: 'Halteres Pesados',
    exercise_type: 'Força de Pegada',
    difficulty: 'Intermediário',
    description: 'Construção maciça de força isométrica na pegada.',
    instructions: 'Segure os halteres o mais firme possível e caminhe mantendo a postura ereta.',
    default_sets: 3,
    default_min_reps: 30,
    default_max_reps: 60,
    default_rest_seconds: 75,
    is_active: 1
  },
  {
    id: 'EX_ANT_007',
    name: 'Hand grip',
    muscle_group: 'Antebraço',
    secondary_muscles: 'Flexores dos dedos',
    equipment: 'Aparelho Hand Grip',
    exercise_type: 'Força de Esmagamento',
    difficulty: 'Iniciante',
    description: 'Apertos no alicate de mola desenvolvendo força de esmagamento.',
    instructions: 'Aperte o hand grip até encostar as alavancas e solte controlando.',
    default_sets: 3,
    default_min_reps: 15,
    default_max_reps: 20,
    default_rest_seconds: 45,
    is_active: 1
  },
  {
    id: 'EX_ANT_008',
    name: 'Pinch grip',
    muscle_group: 'Antebraço',
    secondary_muscles: 'Polegares, Dedos',
    equipment: 'Anilhas Lisas',
    exercise_type: 'Pegada de Pinça',
    difficulty: 'Intermediário',
    description: 'Segurar duas anilhas lisas unidas apenas com a ponta dos dedos.',
    instructions: 'Segure as anilhas em pinça isométrica sem deixar escorregar.',
    default_sets: 3,
    default_min_reps: 20,
    default_max_reps: 40,
    default_rest_seconds: 60,
    is_active: 1
  },

  // ================= Cardio / Condicionamento =================
  {
    id: 'EX_CAR_001',
    name: 'Esteira',
    muscle_group: 'Cardio / condicionamento',
    secondary_muscles: 'Pernas, Sistema Cardiovascular',
    equipment: 'Esteira Ergométrica',
    exercise_type: 'Cardio',
    difficulty: 'Iniciante',
    description: 'Treino cardiovascular aeróbico geral na esteira.',
    instructions: 'Ajuste velocidade e inclinação desejadas mantendo postura ereta.',
    default_sets: 1,
    default_min_reps: 20,
    default_max_reps: 45,
    default_rest_seconds: 0,
    is_active: 1
  },
  {
    id: 'EX_CAR_002',
    name: 'Caminhada na esteira',
    muscle_group: 'Cardio / condicionamento',
    secondary_muscles: 'Pernas',
    equipment: 'Esteira',
    exercise_type: 'Cardio LISS',
    difficulty: 'Iniciante',
    description: 'Caminhada constante de baixo impacto para queima de gordura e recuperação.',
    instructions: 'Caminhe com ritmo vigoroso entre 5 a 6.5 km/h.',
    default_sets: 1,
    default_min_reps: 30,
    default_max_reps: 60,
    default_rest_seconds: 0,
    is_active: 1
  },
  {
    id: 'EX_CAR_003',
    name: 'Corrida na esteira',
    muscle_group: 'Cardio / condicionamento',
    secondary_muscles: 'Pernas, Glúteos',
    equipment: 'Esteira',
    exercise_type: 'Cardio',
    difficulty: 'Intermediário',
    description: 'Corrida contínua aumentando capacidade pulmonar e VO2 max.',
    instructions: 'Corra com passada leve amortecendo o impacto no terço médio do pé.',
    default_sets: 1,
    default_min_reps: 15,
    default_max_reps: 30,
    default_rest_seconds: 0,
    is_active: 1
  },
  {
    id: 'EX_CAR_004',
    name: 'Bicicleta ergométrica',
    muscle_group: 'Cardio / condicionamento',
    secondary_muscles: 'Quadríceps',
    equipment: 'Bicicleta',
    exercise_type: 'Cardio Baixo Impacto',
    difficulty: 'Iniciante',
    description: 'Pedalada contínua sem impacto sobre joelhos e tornozelos.',
    instructions: 'Mantenha cadência regular entre 70 e 90 RPM.',
    default_sets: 1,
    default_min_reps: 20,
    default_max_reps: 40,
    default_rest_seconds: 0,
    is_active: 1
  },
  {
    id: 'EX_CAR_005',
    name: 'Bicicleta vertical',
    muscle_group: 'Cardio / condicionamento',
    secondary_muscles: 'Quadríceps, Glúteos',
    equipment: 'Bicicleta Vertical',
    exercise_type: 'Cardio',
    difficulty: 'Iniciante',
    description: 'Simula o ciclismo tradicional com tronco ligeiramente inclinado.',
    instructions: 'Ajuste a altura do banco no osso do quadril e pedale com ritmo.',
    default_sets: 1,
    default_min_reps: 20,
    default_max_reps: 40,
    default_rest_seconds: 0,
    is_active: 1
  },
  {
    id: 'EX_CAR_006',
    name: 'Bicicleta horizontal',
    muscle_group: 'Cardio / condicionamento',
    secondary_muscles: 'Pernas',
    equipment: 'Bicicleta Horizontal',
    exercise_type: 'Cardio Conforto',
    difficulty: 'Iniciante',
    description: 'Banco com encosto para as costas, ideal para pessoas com dor lombar.',
    instructions: 'Sente-se com as costas apoiadas e pedale com resistência confortável.',
    default_sets: 1,
    default_min_reps: 20,
    default_max_reps: 45,
    default_rest_seconds: 0,
    is_active: 1
  },
  {
    id: 'EX_CAR_007',
    name: 'Spinning',
    muscle_group: 'Cardio / condicionamento',
    secondary_muscles: 'Pernas, Core',
    equipment: 'Bike de Spinning',
    exercise_type: 'Cardio HIIT',
    difficulty: 'Intermediário',
    description: 'Pedalada dinâmica com subidas em pé e giros rápidos.',
    instructions: 'Alterne trechos sentado com alta cadência e trechos em pé com mais carga.',
    default_sets: 1,
    default_min_reps: 30,
    default_max_reps: 50,
    default_rest_seconds: 0,
    is_active: 1
  },
  {
    id: 'EX_CAR_008',
    name: 'Elíptico',
    muscle_group: 'Cardio / condicionamento',
    secondary_muscles: 'Braços, Pernas',
    equipment: 'Elíptico (Transport)',
    exercise_type: 'Cardio Corpo Todo',
    difficulty: 'Iniciante',
    description: 'Movimento simultâneo de pernas e braços sem impacto no solo.',
    instructions: 'Empurre e puxe as hastes enquanto pedala em elipse fluida.',
    default_sets: 1,
    default_min_reps: 20,
    default_max_reps: 40,
    default_rest_seconds: 0,
    is_active: 1
  },
  {
    id: 'EX_CAR_009',
    name: 'Stair climber',
    muscle_group: 'Cardio / condicionamento',
    secondary_muscles: 'Glúteos, Panturrilhas, Coxas',
    equipment: 'Simulador de Escada',
    exercise_type: 'Cardio Alta Intensidade',
    difficulty: 'Intermediário',
    description: 'Subida contínua de degraus para queima calórica intensa e queima de pernas.',
    instructions: 'Suba degrau por degrau sem se apoiar com peso excessivo nos corrimãos.',
    default_sets: 1,
    default_min_reps: 15,
    default_max_reps: 30,
    default_rest_seconds: 0,
    is_active: 1
  },
  {
    id: 'EX_CAR_010',
    name: 'Escada',
    muscle_group: 'Cardio / condicionamento',
    secondary_muscles: 'Glúteos, Pernas',
    equipment: 'Escada / Simulador',
    exercise_type: 'Cardio',
    difficulty: 'Intermediário',
    description: 'Treino de degraus excelente para tonicidade dos glúteos e fôlego.',
    instructions: 'Mantenha os passos firmes e o tronco alinhado.',
    default_sets: 1,
    default_min_reps: 15,
    default_max_reps: 30,
    default_rest_seconds: 0,
    is_active: 1
  },
  {
    id: 'EX_CAR_011',
    name: 'Remo ergométrico',
    muscle_group: 'Cardio / condicionamento',
    secondary_muscles: 'Costas, Pernas, Bíceps, Core',
    equipment: 'Remo Seco / Concept 2',
    exercise_type: 'Cardio Corpo Inteiro',
    difficulty: 'Intermediário',
    description: 'Recruta mais de 85% dos músculos do corpo com tremendo gasto calórico.',
    instructions: 'Empurre forte com as pernas, incline o tronco e puxe com as costas e braços.',
    default_sets: 4,
    default_min_reps: 500,
    default_max_reps: 1000,
    default_rest_seconds: 90,
    is_active: 1
  },
  {
    id: 'EX_CAR_012',
    name: 'Air bike',
    muscle_group: 'Cardio / condicionamento',
    secondary_muscles: 'Corpo Inteiro',
    equipment: 'Air Bike / Assault Bike',
    exercise_type: 'HIIT Extremo',
    difficulty: 'Avançado',
    description: 'Resistência a ar infinita: quanto mais força você coloca, mais pesado fica.',
    instructions: 'Faça tiros de potência máxima empurrando com braços e pernas.',
    default_sets: 6,
    default_min_reps: 20,
    default_max_reps: 30,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_CAR_013',
    name: 'Corrida',
    muscle_group: 'Cardio / condicionamento',
    secondary_muscles: 'Pernas, Core',
    equipment: 'Ar Livre / Pista',
    exercise_type: 'Cardio',
    difficulty: 'Iniciante',
    description: 'Corrida ao ar livre em ritmo contínuo.',
    instructions: 'Mantenha respiração ritmada e postura equilibrada.',
    default_sets: 1,
    default_min_reps: 20,
    default_max_reps: 45,
    default_rest_seconds: 0,
    is_active: 1
  },
  {
    id: 'EX_CAR_014',
    name: 'Caminhada',
    muscle_group: 'Cardio / condicionamento',
    secondary_muscles: 'Pernas',
    equipment: 'Ar Livre',
    exercise_type: 'Cardio LISS',
    difficulty: 'Iniciante',
    description: 'Caminhada ao ar livre excelente para saúde cardiovascular e queima de gordura.',
    instructions: 'Caminhe com ritmo acelerado em postura ereta.',
    default_sets: 1,
    default_min_reps: 30,
    default_max_reps: 60,
    default_rest_seconds: 0,
    is_active: 1
  },
  {
    id: 'EX_CAR_015',
    name: 'Sprints',
    muscle_group: 'Cardio / condicionamento',
    secondary_muscles: 'Isquiotibiais, Glúteos, Potência',
    equipment: 'Pista / Rua',
    exercise_type: 'HIIT / Potência',
    difficulty: 'Avançado',
    description: 'Tiros de velocidade máxima desenvolvem fibras musculares rápidas.',
    instructions: 'Aceleração máxima em 50 a 100 metros com descanso completo entre os tiros.',
    default_sets: 6,
    default_min_reps: 10,
    default_max_reps: 15,
    default_rest_seconds: 90,
    is_active: 1
  },
  {
    id: 'EX_CAR_016',
    name: 'Pular corda',
    muscle_group: 'Cardio / condicionamento',
    secondary_muscles: 'Panturrilhas, Ombros, Coordenação',
    equipment: 'Corda de Pular',
    exercise_type: 'Cardio / Agilidade',
    difficulty: 'Intermediário',
    description: 'Melhora ritmo, agilidade nos pés e condicionamento cardiovascular.',
    instructions: 'Pule na ponta dos pés girando a corda apenas com os punhos.',
    default_sets: 4,
    default_min_reps: 60,
    default_max_reps: 120,
    default_rest_seconds: 45,
    is_active: 1
  },
  {
    id: 'EX_CAR_017',
    name: 'Burpee',
    muscle_group: 'Cardio / condicionamento',
    secondary_muscles: 'Peito, Pernas, Core',
    equipment: 'Peso Corporal',
    exercise_type: 'Calistênico / HIIT',
    difficulty: 'Intermediário',
    description: 'Agacha, joga os pés para trás, faz flexão, volta e salta com as mãos no alto.',
    instructions: 'Transição ágil e contínua mantendo o ritmo sem perder o controle do core.',
    default_sets: 4,
    default_min_reps: 10,
    default_max_reps: 15,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_CAR_018',
    name: 'Jumping jack',
    muscle_group: 'Cardio / condicionamento',
    secondary_muscles: 'Panturrilha, Ombros',
    equipment: 'Peso Corporal',
    exercise_type: 'Aquecimento / Cardio',
    difficulty: 'Iniciante',
    description: 'O clássico polichinelo para aquecimento ou circuitos metabólicos.',
    instructions: 'Abra braços e pernas simultaneamente com saltos leves e cadenciados.',
    default_sets: 3,
    default_min_reps: 30,
    default_max_reps: 60,
    default_rest_seconds: 30,
    is_active: 1
  }
];
