import { ExerciseSeed } from './exerciseData.js';

export const EXERCISES_PART_2: ExerciseSeed[] = [
  // ================= Tríceps =================
  {
    id: 'EX_TRI_001',
    name: 'Tríceps pulley com barra',
    muscle_group: 'Tríceps',
    secondary_muscles: 'Antebraço',
    equipment: 'Polia',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Extensão de cotovelos na polia alta com barra reta ou V.',
    instructions: 'Cotovelos colados ao tronco, empurre a barra para baixo até estender totalmente os braços.',
    default_sets: 4,
    default_min_reps: 10,
    default_max_reps: 12,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_TRI_002',
    name: 'Tríceps pulley com corda',
    muscle_group: 'Tríceps',
    secondary_muscles: 'Antebraço',
    equipment: 'Polia',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Permite afastar as pontas no final do movimento para contração máxima da cabeça lateral.',
    instructions: 'Estenda os braços abrindo a corda no final e segure 1 segundo.',
    default_sets: 4,
    default_min_reps: 10,
    default_max_reps: 15,
    default_rest_seconds: 45,
    is_active: 1
  },
  {
    id: 'EX_TRI_003',
    name: 'Tríceps pulley unilateral',
    muscle_group: 'Tríceps',
    secondary_muscles: 'Antebraço',
    equipment: 'Polia',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Excelente para equalização de força e foco isolado.',
    instructions: 'Puxe com uma mão mantendo o ombro estável e cotovelo apontado para baixo.',
    default_sets: 3,
    default_min_reps: 12,
    default_max_reps: 15,
    default_rest_seconds: 45,
    is_active: 1
  },
  {
    id: 'EX_TRI_004',
    name: 'Tríceps testa com barra',
    muscle_group: 'Tríceps',
    secondary_muscles: 'Ombro anterior',
    equipment: 'Barra W / Reta',
    exercise_type: 'Hipertrofia',
    difficulty: 'Intermediário',
    description: 'Enfatiza a cabeça longa do tríceps com grande alongamento.',
    instructions: 'Deitado no banco, flexione apenas os cotovelos trazendo a barra na direção da testa e estenda.',
    default_sets: 3,
    default_min_reps: 8,
    default_max_reps: 12,
    default_rest_seconds: 75,
    is_active: 1
  },
  {
    id: 'EX_TRI_005',
    name: 'Tríceps testa com halteres',
    muscle_group: 'Tríceps',
    secondary_muscles: 'Antebraço',
    equipment: 'Halteres',
    exercise_type: 'Hipertrofia',
    difficulty: 'Intermediário',
    description: 'Maior liberdade para articulações dos punhos com pegada neutra.',
    instructions: 'Desça os halteres ao lado da cabeça e empurre até a extensão completa.',
    default_sets: 3,
    default_min_reps: 10,
    default_max_reps: 12,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_TRI_006',
    name: 'Tríceps francês unilateral',
    muscle_group: 'Tríceps',
    secondary_muscles: 'Core',
    equipment: 'Halteres',
    exercise_type: 'Hipertrofia',
    difficulty: 'Intermediário',
    description: 'Braço elevado acima da cabeça alongando ao máximo a cabeça longa.',
    instructions: 'Segure o halter atrás da cabeça com uma mão, cotovelo apontando para cima, e estenda o antebraço.',
    default_sets: 3,
    default_min_reps: 10,
    default_max_reps: 12,
    default_rest_seconds: 45,
    is_active: 1
  },
  {
    id: 'EX_TRI_007',
    name: 'Tríceps francês bilateral',
    muscle_group: 'Tríceps',
    secondary_muscles: 'Ombros',
    equipment: 'Halter / Barra',
    exercise_type: 'Hipertrofia',
    difficulty: 'Intermediário',
    description: 'Executado com as duas mãos segurando um halter pesado atrás da cabeça.',
    instructions: 'Mantenha os cotovelos o mais fechados possível e estenda os braços acima da cabeça.',
    default_sets: 3,
    default_min_reps: 10,
    default_max_reps: 12,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_TRI_008',
    name: 'Tríceps acima da cabeça na polia',
    muscle_group: 'Tríceps',
    secondary_muscles: 'Core',
    equipment: 'Polia',
    exercise_type: 'Hipertrofia',
    difficulty: 'Intermediário',
    description: 'Tensão constante em posição de alongamento extremo.',
    instructions: 'De costas para a polia, segure a barra ou manopla e empurre para frente e acima da cabeça.',
    default_sets: 3,
    default_min_reps: 10,
    default_max_reps: 15,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_TRI_009',
    name: 'Tríceps corda acima da cabeça',
    muscle_group: 'Tríceps',
    secondary_muscles: 'Core',
    equipment: 'Polia',
    exercise_type: 'Hipertrofia',
    difficulty: 'Intermediário',
    description: 'Excelente para contração de pico com os braços elevados.',
    instructions: 'Puxe a corda para a frente abrindo no final do movimento.',
    default_sets: 3,
    default_min_reps: 10,
    default_max_reps: 12,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_TRI_010',
    name: 'Tríceps coice com halter',
    muscle_group: 'Tríceps',
    secondary_muscles: 'Dorsal posterior',
    equipment: 'Halteres',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Tronco inclinado, foco no pico de contração com o braço estendido para trás.',
    instructions: 'Cotovelo alto e travado junto ao corpo, estenda o antebraço para trás e aperte o tríceps.',
    default_sets: 3,
    default_min_reps: 12,
    default_max_reps: 15,
    default_rest_seconds: 45,
    is_active: 1
  },
  {
    id: 'EX_TRI_011',
    name: 'Tríceps coice na polia',
    muscle_group: 'Tríceps',
    secondary_muscles: 'Antebraço',
    equipment: 'Polia',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Oferece tensão contínua até no início do movimento.',
    instructions: 'Com a polia baixa ou média, estenda o braço para trás controlando o retorno.',
    default_sets: 3,
    default_min_reps: 12,
    default_max_reps: 15,
    default_rest_seconds: 45,
    is_active: 1
  },
  {
    id: 'EX_TRI_012',
    name: 'Supino fechado',
    muscle_group: 'Tríceps',
    secondary_muscles: 'Peito, Deltoide anterior',
    equipment: 'Barra',
    exercise_type: 'Força/Hipertrofia',
    difficulty: 'Intermediário',
    description: 'Permite trabalhar o tríceps com cargas altas em cadeia cinética fechada.',
    instructions: 'Mãos na largura dos ombros, desça a barra rente ao peito mantendo os cotovelos fechados.',
    default_sets: 4,
    default_min_reps: 6,
    default_max_reps: 10,
    default_rest_seconds: 90,
    is_active: 1
  },
  {
    id: 'EX_TRI_013',
    name: 'Mergulho entre bancos',
    muscle_group: 'Tríceps',
    secondary_muscles: 'Ombro anterior',
    equipment: 'Peso Corporal / Banco',
    exercise_type: 'Resistência/Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Mãos apoiadas no banco de trás e pés no chão ou outro banco.',
    instructions: 'Flexione os cotovelos descendo o quadril rente ao banco e empurre estendendo os braços.',
    default_sets: 3,
    default_min_reps: 10,
    default_max_reps: 15,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_TRI_014',
    name: 'Paralelas para tríceps',
    muscle_group: 'Tríceps',
    secondary_muscles: 'Peito, Ombros',
    equipment: 'Barras Paralelas',
    exercise_type: 'Força/Hipertrofia',
    difficulty: 'Avançado',
    description: 'Tronco vertical para transferir o estímulo predominantemente para o tríceps.',
    instructions: 'Mantenha o corpo reto, desça flexionando os cotovelos e empurre para a posição inicial.',
    default_sets: 3,
    default_min_reps: 8,
    default_max_reps: 12,
    default_rest_seconds: 90,
    is_active: 1
  },
  {
    id: 'EX_TRI_015',
    name: 'Tríceps máquina',
    muscle_group: 'Tríceps',
    secondary_muscles: 'Antebraço',
    equipment: 'Máquina',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Máquina de mergulho ou extensão de tríceps sentado.',
    instructions: 'Ajuste o encosto, empurre as alavancas para baixo estendendo os cotovelos.',
    default_sets: 3,
    default_min_reps: 10,
    default_max_reps: 12,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_TRI_016',
    name: 'Extensão de tríceps na máquina',
    muscle_group: 'Tríceps',
    secondary_muscles: 'Antebraço',
    equipment: 'Máquina',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Braços apoiados em almofada para isolamento estrito.',
    instructions: 'Cotovelos alinhados ao eixo da máquina, estenda os braços com controle.',
    default_sets: 3,
    default_min_reps: 10,
    default_max_reps: 12,
    default_rest_seconds: 60,
    is_active: 1
  },

  // ================= Costas =================
  {
    id: 'EX_COS_001',
    name: 'Barra fixa',
    muscle_group: 'Costas',
    secondary_muscles: 'Bíceps, Antebraço, Core',
    equipment: 'Barra Fixa',
    exercise_type: 'Força/Hipertrofia',
    difficulty: 'Intermediário',
    description: 'O rei dos exercícios de tração para largura de dorsais.',
    instructions: 'Puxe o corpo até o queixo passar da barra e desça controlando o movimento.',
    default_sets: 4,
    default_min_reps: 6,
    default_max_reps: 10,
    default_rest_seconds: 90,
    is_active: 1
  },
  {
    id: 'EX_COS_002',
    name: 'Barra fixa pronada',
    muscle_group: 'Costas',
    secondary_muscles: 'Bíceps, Trapézio',
    equipment: 'Barra Fixa',
    exercise_type: 'Força/Hipertrofia',
    difficulty: 'Intermediário',
    description: 'Palmas para frente, máxima ativação do grande dorsal.',
    instructions: 'Segure um pouco além dos ombros e puxe levando o peito em direção à barra.',
    default_sets: 4,
    default_min_reps: 6,
    default_max_reps: 10,
    default_rest_seconds: 90,
    is_active: 1
  },
  {
    id: 'EX_COS_003',
    name: 'Barra fixa supinada',
    muscle_group: 'Costas',
    secondary_muscles: 'Bíceps (alto recrutamento)',
    equipment: 'Barra Fixa',
    exercise_type: 'Força/Hipertrofia',
    difficulty: 'Intermediário',
    description: 'Palmas voltadas para você (chin-up), forte ativação de dorsais e bíceps.',
    instructions: 'Puxe forte focando em fechar os cotovelos contra as costelas.',
    default_sets: 3,
    default_min_reps: 6,
    default_max_reps: 10,
    default_rest_seconds: 90,
    is_active: 1
  },
  {
    id: 'EX_COS_004',
    name: 'Barra fixa neutra',
    muscle_group: 'Costas',
    secondary_muscles: 'Bíceps, Braquial',
    equipment: 'Barra Fixa',
    exercise_type: 'Força/Hipertrofia',
    difficulty: 'Intermediário',
    description: 'Palmas viradas uma para a outra, muito confortável para os ombros.',
    instructions: 'Segure nas alças paralelas e suba até aproximar o peito das mãos.',
    default_sets: 3,
    default_min_reps: 8,
    default_max_reps: 12,
    default_rest_seconds: 90,
    is_active: 1
  },
  {
    id: 'EX_COS_005',
    name: 'Barra fixa com peso',
    muscle_group: 'Costas',
    secondary_muscles: 'Bíceps, Core',
    equipment: 'Barra Fixa / Cinto com Peso',
    exercise_type: 'Força Máxima',
    difficulty: 'Avançado',
    description: 'Barra fixa com carga externa acoplada por cinto de sobrecarga.',
    instructions: 'Realize o movimento com técnica perfeita sem balanço do tronco.',
    default_sets: 4,
    default_min_reps: 4,
    default_max_reps: 8,
    default_rest_seconds: 120,
    is_active: 1
  },
  {
    id: 'EX_COS_006',
    name: 'Puxada frontal',
    muscle_group: 'Costas',
    secondary_muscles: 'Bíceps, Deltoide posterior',
    equipment: 'Polia',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Puxador alto no pulley com pegada clássica na linha dos ombros.',
    instructions: 'Puxe a barra em direção à parte superior do peito com escápulas ativadas.',
    default_sets: 4,
    default_min_reps: 8,
    default_max_reps: 12,
    default_rest_seconds: 75,
    is_active: 1
  },
  {
    id: 'EX_COS_007',
    name: 'Puxada frontal aberta',
    muscle_group: 'Costas',
    secondary_muscles: 'Bíceps, Redondo maior',
    equipment: 'Polia',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Pegada mais afastada para ênfase na largura do grande dorsal.',
    instructions: 'Segure nas dobras da barra e puxe até o peito sem jogar o tronco para trás.',
    default_sets: 4,
    default_min_reps: 8,
    default_max_reps: 12,
    default_rest_seconds: 75,
    is_active: 1
  },
  {
    id: 'EX_COS_008',
    name: 'Puxada frontal fechada',
    muscle_group: 'Costas',
    secondary_muscles: 'Bíceps, Braquial',
    equipment: 'Polia / Triângulo',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Com triângulo ou pegada fechada, permite grande amplitude.',
    instructions: 'Puxe o triângulo até a altura do queixo/peito alto e contraia as costas.',
    default_sets: 3,
    default_min_reps: 10,
    default_max_reps: 12,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_COS_009',
    name: 'Puxada supinada',
    muscle_group: 'Costas',
    secondary_muscles: 'Bíceps',
    equipment: 'Polia',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Palmas voltadas para o corpo proporcionando alavanca mecânica forte.',
    instructions: 'Puxe a barra até a clavícula mantendo os cotovelos à frente.',
    default_sets: 3,
    default_min_reps: 10,
    default_max_reps: 12,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_COS_010',
    name: 'Puxada neutra',
    muscle_group: 'Costas',
    secondary_muscles: 'Bíceps, Braquiorradial',
    equipment: 'Polia / Barra H',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Pegada neutra na barra média ou alças duplas.',
    instructions: 'Puxe mantendo a coluna ereta e sinta a compressão escapular.',
    default_sets: 3,
    default_min_reps: 10,
    default_max_reps: 12,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_COS_011',
    name: 'Puxada unilateral',
    muscle_group: 'Costas',
    secondary_muscles: 'Bíceps, Core',
    equipment: 'Polia',
    exercise_type: 'Hipertrofia',
    difficulty: 'Intermediário',
    description: 'Puxada com uma manopla, excelente para correção de assimetrias.',
    instructions: 'Puxe alinhando o cotovelo ao quadril e retorne alongando a dorsal.',
    default_sets: 3,
    default_min_reps: 10,
    default_max_reps: 12,
    default_rest_seconds: 45,
    is_active: 1
  },
  {
    id: 'EX_COS_012',
    name: 'Puxada na máquina',
    muscle_group: 'Costas',
    secondary_muscles: 'Bíceps',
    equipment: 'Máquina',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Máquina convergente articulada para puxada alta.',
    instructions: 'Puxe os apoios para baixo focando na depressão e adução das escápulas.',
    default_sets: 3,
    default_min_reps: 10,
    default_max_reps: 12,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_COS_013',
    name: 'Remada curvada com barra',
    muscle_group: 'Costas',
    secondary_muscles: 'Lombar, Trapézio, Bíceps',
    equipment: 'Barra',
    exercise_type: 'Força/Hipertrofia',
    difficulty: 'Intermediário',
    description: 'Exercício primordial para espessura e força geral das costas.',
    instructions: 'Tronco inclinado a 45 graus, coluna neutra, puxe a barra na direção do umbigo.',
    default_sets: 4,
    default_min_reps: 8,
    default_max_reps: 10,
    default_rest_seconds: 90,
    is_active: 1
  },
  {
    id: 'EX_COS_014',
    name: 'Remada curvada supinada',
    muscle_group: 'Costas',
    secondary_muscles: 'Bíceps, Dorsal inferior',
    equipment: 'Barra',
    exercise_type: 'Hipertrofia',
    difficulty: 'Intermediário',
    description: 'Pegada invertida que permite fechar mais os cotovelos contra o tronco.',
    instructions: 'Puxe a barra rente às coxas até encostar no abdômen inferior.',
    default_sets: 3,
    default_min_reps: 8,
    default_max_reps: 12,
    default_rest_seconds: 90,
    is_active: 1
  },
  {
    id: 'EX_COS_015',
    name: 'Remada unilateral com halter',
    muscle_group: 'Costas',
    secondary_muscles: 'Bíceps, Antebraço',
    equipment: 'Halteres / Banco',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'O famoso serrote, com apoio no banco e grande amplitude.',
    instructions: 'Com joelho e mão apoiados, puxe o halter levando o cotovelo em direção ao bolso da calça.',
    default_sets: 3,
    default_min_reps: 10,
    default_max_reps: 12,
    default_rest_seconds: 45,
    is_active: 1
  },
  {
    id: 'EX_COS_016',
    name: 'Remada cavalinho',
    muscle_group: 'Costas',
    secondary_muscles: 'Lombar, Trapézio, Bíceps',
    equipment: 'Barra T / Landmine',
    exercise_type: 'Força/Hipertrofia',
    difficulty: 'Intermediário',
    description: 'Excelente para densidade no meio das costas.',
    instructions: 'Posicione-se sobre a barra T, puxe o triângulo no abdômen e aperte as escápulas.',
    default_sets: 4,
    default_min_reps: 8,
    default_max_reps: 12,
    default_rest_seconds: 90,
    is_active: 1
  },
  {
    id: 'EX_COS_017',
    name: 'Remada cavalinho com apoio',
    muscle_group: 'Costas',
    secondary_muscles: 'Trapézio, Romboides',
    equipment: 'Máquina Barra T',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Peito apoiado na almofada eliminando qualquer sobrecarga na coluna lombar.',
    instructions: 'Puxe as alças mantendo o peitoral firme no apoio.',
    default_sets: 3,
    default_min_reps: 10,
    default_max_reps: 12,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_COS_018',
    name: 'Remada baixa',
    muscle_group: 'Costas',
    secondary_muscles: 'Bíceps, Romboides',
    equipment: 'Polia',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Remada no pulley sentado para densidade e controle.',
    instructions: 'Pernas semiflexionadas, puxe o pegador até o abdômen e estufe o peito.',
    default_sets: 4,
    default_min_reps: 10,
    default_max_reps: 12,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_COS_019',
    name: 'Remada baixa fechada',
    muscle_group: 'Costas',
    secondary_muscles: 'Bíceps, Grande dorsal',
    equipment: 'Polia / Triângulo',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Pegada com triângulo no pulley sentado.',
    instructions: 'Mantenha os cotovelos rentes ao tronco e puxe até o umbigo.',
    default_sets: 3,
    default_min_reps: 10,
    default_max_reps: 12,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_COS_020',
    name: 'Remada baixa aberta',
    muscle_group: 'Costas',
    secondary_muscles: 'Deltoide posterior, Trapézio médio',
    equipment: 'Polia / Barra Reta',
    exercise_type: 'Hipertrofia',
    difficulty: 'Intermediário',
    description: 'Barra reta com pegada aberta no pulley sentado.',
    instructions: 'Puxe com cotovelos abertos na altura do esterno para atingir a parte superior das costas.',
    default_sets: 3,
    default_min_reps: 10,
    default_max_reps: 12,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_COS_021',
    name: 'Remada unilateral na polia',
    muscle_group: 'Costas',
    secondary_muscles: 'Bíceps',
    equipment: 'Polia',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Trabalho concentrado permitindo rotação do punho de pronado para neutro.',
    instructions: 'Puxe a manopla girando o punho e levando o cotovelo para trás.',
    default_sets: 3,
    default_min_reps: 10,
    default_max_reps: 12,
    default_rest_seconds: 45,
    is_active: 1
  },
  {
    id: 'EX_COS_022',
    name: 'Remada máquina',
    muscle_group: 'Costas',
    secondary_muscles: 'Bíceps',
    equipment: 'Máquina',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Apoio peitoral seguro e movimento biomecânico estável.',
    instructions: 'Segure as manoplas e puxe com as costas, sem puxar com os ombros encolhidos.',
    default_sets: 3,
    default_min_reps: 10,
    default_max_reps: 12,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_COS_023',
    name: 'Remada articulada',
    muscle_group: 'Costas',
    secondary_muscles: 'Bíceps, Trapézio',
    equipment: 'Máquina Articulada',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Alavancas independentes carregadas por anilhas.',
    instructions: 'Execute a puxada de forma bilateral ou unilateral com foco na contração.',
    default_sets: 3,
    default_min_reps: 8,
    default_max_reps: 12,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_COS_024',
    name: 'Pullover com halter',
    muscle_group: 'Costas',
    secondary_muscles: 'Peito, Tríceps longo',
    equipment: 'Halteres / Banco',
    exercise_type: 'Hipertrofia',
    difficulty: 'Intermediário',
    description: 'Movimento em arco que alonga profundamente o grande dorsal.',
    instructions: 'Deitado de través no banco, desça o halter atrás da cabeça e volte até a linha dos olhos.',
    default_sets: 3,
    default_min_reps: 10,
    default_max_reps: 12,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_COS_025',
    name: 'Pullover na polia',
    muscle_group: 'Costas',
    secondary_muscles: 'Tríceps',
    equipment: 'Polia',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Pullover em pé na polia alta com barra ou corda.',
    instructions: 'Cotovelos semiflexionados, empurre a barra em arco para baixo até encostar nas coxas.',
    default_sets: 3,
    default_min_reps: 12,
    default_max_reps: 15,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_COS_026',
    name: 'Pulldown na polia',
    muscle_group: 'Costas',
    secondary_muscles: 'Abdômen',
    equipment: 'Polia',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Excelente para conexão mente-músculo com o grande dorsal sem cansar o bíceps.',
    instructions: 'Incline o tronco levemente à frente e puxe a barra estendendo até o quadril.',
    default_sets: 3,
    default_min_reps: 12,
    default_max_reps: 15,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_COS_027',
    name: 'Straight-arm pulldown',
    muscle_group: 'Costas',
    secondary_muscles: 'Tríceps longo',
    equipment: 'Polia',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Braços retos trabalhando isoladamente a adução do ombro pela dorsal.',
    instructions: 'Pressione a barra para baixo mantendo os braços firmes e sinta o dorsal queimar.',
    default_sets: 3,
    default_min_reps: 12,
    default_max_reps: 15,
    default_rest_seconds: 60,
    is_active: 1
  }
];
