export interface ExerciseSeed {
  id: string;
  name: string;
  muscle_group: string;
  secondary_muscles: string;
  equipment: string;
  exercise_type: string;
  difficulty: 'Iniciante' | 'Intermediário' | 'Avançado';
  description: string;
  instructions: string;
  default_sets: number;
  default_min_reps: number;
  default_max_reps: number;
  default_rest_seconds: number;
  is_active: number;
}

export const ALL_EXERCISES: ExerciseSeed[] = [
  // ================= Peito =================
  {
    id: 'EX_PEITO_001',
    name: 'Supino reto com barra',
    muscle_group: 'Peito',
    secondary_muscles: 'Tríceps, Deltoide anterior',
    equipment: 'Barra',
    exercise_type: 'Força/Hipertrofia',
    difficulty: 'Intermediário',
    description: 'Exercício composto fundamental para construção de força e densidade peitoral.',
    instructions: 'Deite-se no banco, pés firmes no chão, desça a barra até tocar suavemente a linha dos mamilos e empurre estendendo os braços com controle.',
    default_sets: 4,
    default_min_reps: 8,
    default_max_reps: 12,
    default_rest_seconds: 90,
    is_active: 1
  },
  {
    id: 'EX_PEITO_002',
    name: 'Supino inclinado com barra',
    muscle_group: 'Peito',
    secondary_muscles: 'Deltoide anterior, Tríceps',
    equipment: 'Barra',
    exercise_type: 'Força/Hipertrofia',
    difficulty: 'Intermediário',
    description: 'Enfatiza a porção clavicular (superior) do peitoral.',
    instructions: 'Banco ajustado a cerca de 30-45 graus. Desça a barra até a parte superior do peito e suba verticalmente.',
    default_sets: 4,
    default_min_reps: 8,
    default_max_reps: 12,
    default_rest_seconds: 90,
    is_active: 1
  },
  {
    id: 'EX_PEITO_003',
    name: 'Supino declinado com barra',
    muscle_group: 'Peito',
    secondary_muscles: 'Tríceps, Deltoide anterior',
    equipment: 'Barra',
    exercise_type: 'Hipertrofia',
    difficulty: 'Intermediário',
    description: 'Foco na porção inferior (costal) do músculo peitoral maior.',
    instructions: 'Em banco declinado com tornozelos travados, execute a descida controlada e empurre mantendo a estabilidade do tronco.',
    default_sets: 3,
    default_min_reps: 8,
    default_max_reps: 12,
    default_rest_seconds: 75,
    is_active: 1
  },
  {
    id: 'EX_PEITO_004',
    name: 'Supino reto com halteres',
    muscle_group: 'Peito',
    secondary_muscles: 'Tríceps, Deltoide anterior',
    equipment: 'Halteres',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Permite maior amplitude de movimento articular e correção de assimetrias.',
    instructions: 'Inicie com os halteres na altura do peito e empurre convergindo levemente no topo sem bater os pesos.',
    default_sets: 4,
    default_min_reps: 8,
    default_max_reps: 12,
    default_rest_seconds: 75,
    is_active: 1
  },
  {
    id: 'EX_PEITO_005',
    name: 'Supino inclinado com halteres',
    muscle_group: 'Peito',
    secondary_muscles: 'Deltoide anterior, Tríceps',
    equipment: 'Halteres',
    exercise_type: 'Hipertrofia',
    difficulty: 'Intermediário',
    description: 'Maior recrutamento da porção superior com liberdade de punhos e cotovelos.',
    instructions: 'Banco a 30-45 graus. Empurre os halteres para cima e controle o alongamento na fase excêntrica.',
    default_sets: 3,
    default_min_reps: 8,
    default_max_reps: 12,
    default_rest_seconds: 75,
    is_active: 1
  },
  {
    id: 'EX_PEITO_006',
    name: 'Supino declinado com halteres',
    muscle_group: 'Peito',
    secondary_muscles: 'Tríceps',
    equipment: 'Halteres',
    exercise_type: 'Hipertrofia',
    difficulty: 'Intermediário',
    description: 'Trabalho do peitoral inferior com movimento livre e natural dos halteres.',
    instructions: 'Deite-se no banco declinado e empurre os halteres para cima, controlando a descida.',
    default_sets: 3,
    default_min_reps: 10,
    default_max_reps: 12,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_PEITO_007',
    name: 'Supino na máquina',
    muscle_group: 'Peito',
    secondary_muscles: 'Tríceps, Deltoide anterior',
    equipment: 'Máquina',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Ótimo para isolamento e segurança em cargas mais altas sem risco de queda.',
    instructions: 'Ajuste o assento para que as manoplas fiquem na linha do peito. Empurre e contraia o peitoral.',
    default_sets: 3,
    default_min_reps: 10,
    default_max_reps: 12,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_PEITO_008',
    name: 'Supino inclinado na máquina',
    muscle_group: 'Peito',
    secondary_muscles: 'Deltoide anterior, Tríceps',
    equipment: 'Máquina',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Trajetória guiada focando peitoral superior com estabilidade.',
    instructions: 'Mantenha as escápulas aduzidas e empurre a máquina com ênfase no peito alto.',
    default_sets: 3,
    default_min_reps: 10,
    default_max_reps: 12,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_PEITO_009',
    name: 'Chest press',
    muscle_group: 'Peito',
    secondary_muscles: 'Tríceps, Deltoide anterior',
    equipment: 'Máquina',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Máquina de empurrar convergente para estímulo constante.',
    instructions: 'Sente-se com as costas apoiadas, segure as manoplas e realize a extensão dos cotovelos.',
    default_sets: 3,
    default_min_reps: 10,
    default_max_reps: 12,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_PEITO_010',
    name: 'Chest press inclinado',
    muscle_group: 'Peito',
    secondary_muscles: 'Deltoide anterior',
    equipment: 'Máquina',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Press inclinado guiado com movimento convergente.',
    instructions: 'Ajuste a altura do banco e empurre na direção diagonal ascendente.',
    default_sets: 3,
    default_min_reps: 10,
    default_max_reps: 12,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_PEITO_011',
    name: 'Crucifixo com halteres',
    muscle_group: 'Peito',
    secondary_muscles: 'Deltoide anterior',
    equipment: 'Halteres',
    exercise_type: 'Hipertrofia',
    difficulty: 'Intermediário',
    description: 'Excelente para alongamento sob tensão máxima das fibras peitorais.',
    instructions: 'Deitado no banco, abra os braços mantendo os cotovelos levemente flexionados, até sentir o peito alongar bem, e feche em arco.',
    default_sets: 3,
    default_min_reps: 10,
    default_max_reps: 15,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_PEITO_012',
    name: 'Crucifixo inclinado',
    muscle_group: 'Peito',
    secondary_muscles: 'Deltoide anterior',
    equipment: 'Halteres',
    exercise_type: 'Hipertrofia',
    difficulty: 'Intermediário',
    description: 'Alongamento das fibras superiores do peitoral com movimento de arco.',
    instructions: 'Em banco inclinado, abra os halteres com cotovelos semiflexionados e retorne focando na contração.',
    default_sets: 3,
    default_min_reps: 10,
    default_max_reps: 12,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_PEITO_013',
    name: 'Crucifixo na máquina',
    muscle_group: 'Peito',
    secondary_muscles: 'Deltoide anterior',
    equipment: 'Máquina',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Movimento de adução horizontal guiado com tensão mecânica constante.',
    instructions: 'Costas bem apoiadas, braços abertos alinhados com o peito, feche as alavancas à frente.',
    default_sets: 3,
    default_min_reps: 12,
    default_max_reps: 15,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_PEITO_014',
    name: 'Peck deck',
    muscle_group: 'Peito',
    secondary_muscles: 'Deltoide anterior',
    equipment: 'Máquina',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Voador clássico para pico de contração no meio do peitoral.',
    instructions: 'Apoie os antebraços ou mãos nas almofadas, feche aproximando os cotovelos e segure 1s na contração máxima.',
    default_sets: 3,
    default_min_reps: 12,
    default_max_reps: 15,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_PEITO_015',
    name: 'Crossover na polia alta',
    muscle_group: 'Peito',
    secondary_muscles: 'Deltoide anterior',
    equipment: 'Polia',
    exercise_type: 'Hipertrofia',
    difficulty: 'Intermediário',
    description: 'Tensão contínua com ênfase na porção inferior e média do peitoral.',
    instructions: 'Tronco ligeiramente inclinado à frente, puxe as manoplas de cima para baixo cruzando ou tocando as mãos na frente da cintura.',
    default_sets: 3,
    default_min_reps: 12,
    default_max_reps: 15,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_PEITO_016',
    name: 'Crossover na polia baixa',
    muscle_group: 'Peito',
    secondary_muscles: 'Deltoide anterior',
    equipment: 'Polia',
    exercise_type: 'Hipertrofia',
    difficulty: 'Intermediário',
    description: 'Excelente para porção superior e miolo do peitoral.',
    instructions: 'Polias posicionadas na base, puxe as manoplas de baixo para cima até a altura do queixo.',
    default_sets: 3,
    default_min_reps: 12,
    default_max_reps: 15,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_PEITO_017',
    name: 'Crossover unilateral',
    muscle_group: 'Peito',
    secondary_muscles: 'Core, Deltoide anterior',
    equipment: 'Polia',
    exercise_type: 'Hipertrofia',
    difficulty: 'Intermediário',
    description: 'Permite maior amplitude e foco concentrado em cada lado.',
    instructions: 'Execute a adução cruzando além da linha média do corpo para máxima contração.',
    default_sets: 3,
    default_min_reps: 12,
    default_max_reps: 15,
    default_rest_seconds: 45,
    is_active: 1
  },
  {
    id: 'EX_PEITO_018',
    name: 'Crossover de baixo para cima',
    muscle_group: 'Peito',
    secondary_muscles: 'Deltoide anterior',
    equipment: 'Polia',
    exercise_type: 'Hipertrofia',
    difficulty: 'Intermediário',
    description: 'Foco na ativação das fibras claviculares.',
    instructions: 'Partindo de baixo, eleve os braços em rotação interna suave até o centro do tórax.',
    default_sets: 3,
    default_min_reps: 10,
    default_max_reps: 12,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_PEITO_019',
    name: 'Flexão tradicional',
    muscle_group: 'Peito',
    secondary_muscles: 'Tríceps, Abdômen, Ombros',
    equipment: 'Peso Corporal',
    exercise_type: 'Resistência/Força',
    difficulty: 'Iniciante',
    description: 'Exercício calistênico básico com grande ativação muscular.',
    instructions: 'Corpo alinhado em prancha, mãos na largura dos ombros, desça o peito próximo ao solo e empurre.',
    default_sets: 3,
    default_min_reps: 10,
    default_max_reps: 20,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_PEITO_020',
    name: 'Flexão inclinada',
    muscle_group: 'Peito',
    secondary_muscles: 'Tríceps',
    equipment: 'Peso Corporal',
    exercise_type: 'Resistência',
    difficulty: 'Iniciante',
    description: 'Mãos apoiadas em um banco elevado, facilitando a execução.',
    instructions: 'Mantenha o corpo reto e empurre a partir do banco, com ênfase na parte inferior.',
    default_sets: 3,
    default_min_reps: 12,
    default_max_reps: 20,
    default_rest_seconds: 45,
    is_active: 1
  },
  {
    id: 'EX_PEITO_021',
    name: 'Flexão declinada',
    muscle_group: 'Peito',
    secondary_muscles: 'Deltoide anterior, Tríceps',
    equipment: 'Peso Corporal',
    exercise_type: 'Força',
    difficulty: 'Intermediário',
    description: 'Pés elevados no banco para transferir carga para a porção superior.',
    instructions: 'Pés no banco e mãos no solo, realize a flexão controlada.',
    default_sets: 3,
    default_min_reps: 8,
    default_max_reps: 15,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_PEITO_022',
    name: 'Flexão com pegada aberta',
    muscle_group: 'Peito',
    secondary_muscles: 'Ombros',
    equipment: 'Peso Corporal',
    exercise_type: 'Hipertrofia',
    difficulty: 'Intermediário',
    description: 'Mãos mais afastadas aumentam o estiramento horizontal do peitoral.',
    instructions: 'Afaste as mãos além da linha dos ombros e execute a flexão.',
    default_sets: 3,
    default_min_reps: 10,
    default_max_reps: 15,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_PEITO_023',
    name: 'Flexão com pegada fechada',
    muscle_group: 'Peito',
    secondary_muscles: 'Tríceps',
    equipment: 'Peso Corporal',
    exercise_type: 'Hipertrofia',
    difficulty: 'Intermediário',
    description: 'Pegada mais estreita aumenta o trabalho do peito medial e tríceps.',
    instructions: 'Mãos posicionadas na largura do peito, mantendo os cotovelos rentes ao tronco.',
    default_sets: 3,
    default_min_reps: 8,
    default_max_reps: 15,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_PEITO_024',
    name: 'Flexão diamante',
    muscle_group: 'Peito',
    secondary_muscles: 'Tríceps',
    equipment: 'Peso Corporal',
    exercise_type: 'Força/Hipertrofia',
    difficulty: 'Avançado',
    description: 'Dedos indicadores e polegares juntos formando um losango.',
    instructions: 'Desça o peito até tocar as mãos e empurre com força de tríceps e peitoral medial.',
    default_sets: 3,
    default_min_reps: 6,
    default_max_reps: 12,
    default_rest_seconds: 75,
    is_active: 1
  },
  {
    id: 'EX_PEITO_025',
    name: 'Flexão com carga',
    muscle_group: 'Peito',
    secondary_muscles: 'Tríceps, Core',
    equipment: 'Peso Corporal / Anilha',
    exercise_type: 'Força',
    difficulty: 'Avançado',
    description: 'Flexão com anilha ou colete com sobrecarga no dorso.',
    instructions: 'Com uma anilha segura sobre a região escapular, realize a flexão estrita.',
    default_sets: 3,
    default_min_reps: 6,
    default_max_reps: 10,
    default_rest_seconds: 90,
    is_active: 1
  },
  {
    id: 'EX_PEITO_026',
    name: 'Flexão explosiva',
    muscle_group: 'Peito',
    secondary_muscles: 'Tríceps, Potência',
    equipment: 'Peso Corporal',
    exercise_type: 'Potência/Pliometria',
    difficulty: 'Avançado',
    description: 'Trabalho de potência de membros superiores (com palma ou descolamento das mãos).',
    instructions: 'Desça controlado e empurre o solo com máxima velocidade descolando as mãos do chão.',
    default_sets: 4,
    default_min_reps: 5,
    default_max_reps: 8,
    default_rest_seconds: 90,
    is_active: 1
  },
  {
    id: 'EX_PEITO_027',
    name: 'Dips para peito',
    muscle_group: 'Peito',
    secondary_muscles: 'Tríceps, Deltoide anterior',
    equipment: 'Barras Paralelas',
    exercise_type: 'Força/Hipertrofia',
    difficulty: 'Avançado',
    description: 'Paralelas com inclinação do tronco para frente com grande estímulo no peito.',
    instructions: 'Incline o tronco para frente, cotovelos levemente abertos, desça até 90 graus e suba.',
    default_sets: 3,
    default_min_reps: 6,
    default_max_reps: 12,
    default_rest_seconds: 90,
    is_active: 1
  }
];
