import { ExerciseSeed } from './exerciseData.js';

export const EXERCISES_PART_3: ExerciseSeed[] = [
  // ================= Bíceps =================
  {
    id: 'EX_BIC_001',
    name: 'Rosca direta com barra',
    muscle_group: 'Bíceps',
    secondary_muscles: 'Antebraço',
    equipment: 'Barra',
    exercise_type: 'Força/Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Construtor clássico de massa para o bíceps braquial.',
    instructions: 'Cotovelos junto ao tronco, suba a barra até a flexão máxima do cotovelo e desça controlando.',
    default_sets: 4,
    default_min_reps: 8,
    default_max_reps: 12,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_BIC_002',
    name: 'Rosca direta com barra W',
    muscle_group: 'Bíceps',
    secondary_muscles: 'Antebraço',
    equipment: 'Barra W',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'A pegada semi-pronada reduz a pressão sobre os punhos.',
    instructions: 'Segure na curvatura da barra W e realize a rosca com movimento estrito.',
    default_sets: 3,
    default_min_reps: 8,
    default_max_reps: 12,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_BIC_003',
    name: 'Rosca direta na polia',
    muscle_group: 'Bíceps',
    secondary_muscles: 'Antebraço',
    equipment: 'Polia',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Tensão constante em todo o arco de movimento, inclusive no início e topo.',
    instructions: 'Conecte a barra na polia baixa e flexione os cotovelos mantendo a postura firme.',
    default_sets: 3,
    default_min_reps: 10,
    default_max_reps: 12,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_BIC_004',
    name: 'Rosca alternada',
    muscle_group: 'Bíceps',
    secondary_muscles: 'Antebraço, Braquial',
    equipment: 'Halteres',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Permite rotação de punho (supinação) para máxima ativação.',
    instructions: 'Inicie com pegada neutra e gire o punho para cima conforme sobe o halter.',
    default_sets: 3,
    default_min_reps: 10,
    default_max_reps: 12,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_BIC_005',
    name: 'Rosca simultânea',
    muscle_group: 'Bíceps',
    secondary_muscles: 'Antebraço',
    equipment: 'Halteres',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Ambos os braços flexionando simultaneamente para manter o músculo sob tensão.',
    instructions: 'Suba ambos os halteres ao mesmo tempo, sem usar embalo do quadril.',
    default_sets: 3,
    default_min_reps: 10,
    default_max_reps: 12,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_BIC_006',
    name: 'Rosca martelo',
    muscle_group: 'Bíceps',
    secondary_muscles: 'Braquial, Braquiorradial',
    equipment: 'Halteres',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Pegada neutra que desenvolve a espessura do braço e antebraço.',
    instructions: 'Segure os halteres como martelos e suba sem girar os punhos.',
    default_sets: 3,
    default_min_reps: 10,
    default_max_reps: 12,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_BIC_007',
    name: 'Rosca martelo alternada',
    muscle_group: 'Bíceps',
    secondary_muscles: 'Braquial, Braquiorradial',
    equipment: 'Halteres',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Martelo executado alternando os braços com foco total em cada repetição.',
    instructions: 'Suba um halter de cada vez mantendo a pegada neutra firme.',
    default_sets: 3,
    default_min_reps: 10,
    default_max_reps: 12,
    default_rest_seconds: 45,
    is_active: 1
  },
  {
    id: 'EX_BIC_008',
    name: 'Rosca martelo na polia',
    muscle_group: 'Bíceps',
    secondary_muscles: 'Braquial',
    equipment: 'Polia / Corda',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Com corda na polia baixa garantindo tensão constante no braquial.',
    instructions: 'Puxe as pontas da corda para cima mantendo os polegares apontados para o teto.',
    default_sets: 3,
    default_min_reps: 10,
    default_max_reps: 15,
    default_rest_seconds: 45,
    is_active: 1
  },
  {
    id: 'EX_BIC_009',
    name: 'Rosca concentrada',
    muscle_group: 'Bíceps',
    secondary_muscles: 'Antebraço',
    equipment: 'Halteres / Banco',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Cotovelo apoiado na face interna da coxa eliminando trapaças.',
    instructions: 'Sentado com pernas abertas, apoie o cotovelo e flexione o braço até a contração máxima.',
    default_sets: 3,
    default_min_reps: 10,
    default_max_reps: 12,
    default_rest_seconds: 45,
    is_active: 1
  },
  {
    id: 'EX_BIC_010',
    name: 'Rosca Scott',
    muscle_group: 'Bíceps',
    secondary_muscles: 'Braquial',
    equipment: 'Banco Scott / Halter',
    exercise_type: 'Hipertrofia',
    difficulty: 'Intermediário',
    description: 'Braços fixados na almofada inclinada focando na porção distal do bíceps.',
    instructions: 'Apoie o tríceps na almofada e realize a flexão sem levantar os cotovelos.',
    default_sets: 3,
    default_min_reps: 8,
    default_max_reps: 12,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_BIC_011',
    name: 'Rosca Scott com barra',
    muscle_group: 'Bíceps',
    secondary_muscles: 'Braquial',
    equipment: 'Banco Scott / Barra W',
    exercise_type: 'Hipertrofia',
    difficulty: 'Intermediário',
    description: 'Execução estrita com barra W no banco Scott.',
    instructions: 'Desça até estender quase que completamente e puxe contraindo no topo.',
    default_sets: 3,
    default_min_reps: 8,
    default_max_reps: 12,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_BIC_012',
    name: 'Rosca Scott na máquina',
    muscle_group: 'Bíceps',
    secondary_muscles: 'Braquial',
    equipment: 'Máquina',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Movimento guiado com resistência contínua até o final do curso.',
    instructions: 'Ajuste o assento e puxe as alavancas mantendo o peito apoiado.',
    default_sets: 3,
    default_min_reps: 10,
    default_max_reps: 12,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_BIC_013',
    name: 'Rosca Scott unilateral',
    muscle_group: 'Bíceps',
    secondary_muscles: 'Braquial',
    equipment: 'Banco Scott / Halter',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Foco unilateral isolando o trabalho de cada braço.',
    instructions: 'Apoie um braço por vez e execute o movimento concentrado.',
    default_sets: 3,
    default_min_reps: 10,
    default_max_reps: 12,
    default_rest_seconds: 45,
    is_active: 1
  },
  {
    id: 'EX_BIC_014',
    name: 'Rosca inclinada com halteres',
    muscle_group: 'Bíceps',
    secondary_muscles: 'Deltoide anterior',
    equipment: 'Halteres / Banco Inclinado',
    exercise_type: 'Hipertrofia',
    difficulty: 'Intermediário',
    description: 'O posicionamento dos cotovelos atrás do corpo enfatiza o alongamento da cabeça longa.',
    instructions: 'Banco a 45-60 graus. Deixe os braços caírem para trás e suba flexionando com supinação.',
    default_sets: 3,
    default_min_reps: 10,
    default_max_reps: 12,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_BIC_015',
    name: 'Rosca spider',
    muscle_group: 'Bíceps',
    secondary_muscles: 'Braquial',
    equipment: 'Halteres / Banco Inclinado',
    exercise_type: 'Hipertrofia',
    difficulty: 'Intermediário',
    description: 'Peito apoiado no banco inclinado, braços verticais para pico de contração.',
    instructions: 'Com os braços pendendo para frente, flexione os cotovelos espremendo o pico do bíceps.',
    default_sets: 3,
    default_min_reps: 10,
    default_max_reps: 12,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_BIC_016',
    name: 'Rosca 21',
    muscle_group: 'Bíceps',
    secondary_muscles: 'Antebraço',
    equipment: 'Barra W / Reta',
    exercise_type: 'Resistência/Hipertrofia',
    difficulty: 'Avançado',
    description: 'Método com 7 reps na metade inferior, 7 na metade superior e 7 completas.',
    instructions: 'Complete as 21 repetições ininterruptas para pump e estresse metabólico extremo.',
    default_sets: 3,
    default_min_reps: 21,
    default_max_reps: 21,
    default_rest_seconds: 90,
    is_active: 1
  },
  {
    id: 'EX_BIC_017',
    name: 'Rosca inversa',
    muscle_group: 'Bíceps',
    secondary_muscles: 'Braquiorradial, Extensores de Punho',
    equipment: 'Barra / Halteres',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Pegada pronada (palmas para baixo) focando em antebraço e braquial.',
    instructions: 'Segure a barra com palmas para baixo e levante sem mover os cotovelos.',
    default_sets: 3,
    default_min_reps: 10,
    default_max_reps: 15,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_BIC_018',
    name: 'Rosca inversa com barra',
    muscle_group: 'Bíceps',
    secondary_muscles: 'Antebraço',
    equipment: 'Barra W',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Construção maciça da parte superior dos antebraços.',
    instructions: 'Utilize barra W pronada e suba controlando a rotação dos punhos.',
    default_sets: 3,
    default_min_reps: 10,
    default_max_reps: 12,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_BIC_019',
    name: 'Rosca unilateral na polia',
    muscle_group: 'Bíceps',
    secondary_muscles: 'Antebraço',
    equipment: 'Polia',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Trabalho contínuo em cada braço usando a polia baixa.',
    instructions: 'Mantenha o corpo estável e puxe a manopla até o ombro.',
    default_sets: 3,
    default_min_reps: 10,
    default_max_reps: 12,
    default_rest_seconds: 45,
    is_active: 1
  },
  {
    id: 'EX_BIC_020',
    name: 'Rosca Bayesian',
    muscle_group: 'Bíceps',
    secondary_muscles: 'Deltoide anterior',
    equipment: 'Polia',
    exercise_type: 'Hipertrofia',
    difficulty: 'Avançado',
    description: 'Executada de costas para o cabo na polia baixa com o braço estendido para trás.',
    instructions: 'Dê um passo à frente da polia, sinta o bíceps alongado e flexione para frente.',
    default_sets: 3,
    default_min_reps: 10,
    default_max_reps: 12,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_BIC_021',
    name: 'Rosca drag',
    muscle_group: 'Bíceps',
    secondary_muscles: 'Deltoide posterior',
    equipment: 'Barra',
    exercise_type: 'Hipertrofia',
    difficulty: 'Intermediário',
    description: 'Arrastando a barra rente ao abdômen e peito, jogando os cotovelos para trás.',
    instructions: 'Puxe a barra para cima rente ao tronco empurrando os cotovelos para trás.',
    default_sets: 3,
    default_min_reps: 10,
    default_max_reps: 12,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_BIC_022',
    name: 'Rosca Zottman',
    muscle_group: 'Bíceps',
    secondary_muscles: 'Braquiorradial, Antebraço',
    equipment: 'Halteres',
    exercise_type: 'Hipertrofia',
    difficulty: 'Intermediário',
    description: 'Sobe com pegada supinada e desce com pegada pronada.',
    instructions: 'Suba como rosca normal, no topo gire os punhos para baixo e desça resistindo ao peso.',
    default_sets: 3,
    default_min_reps: 8,
    default_max_reps: 12,
    default_rest_seconds: 60,
    is_active: 1
  },

  // ================= Quadríceps =================
  {
    id: 'EX_QUA_001',
    name: 'Agachamento livre',
    muscle_group: 'Quadríceps',
    secondary_muscles: 'Glúteos, Core, Posterior',
    equipment: 'Barra / Gaiola',
    exercise_type: 'Força/Hipertrofia',
    difficulty: 'Intermediário',
    description: 'O exercício padrão ouro para força e desenvolvimento de pernas.',
    instructions: 'Pés na largura dos ombros, desça flexionando joelhos e quadril mantendo peito aberto até passar dos 90 graus.',
    default_sets: 4,
    default_min_reps: 6,
    default_max_reps: 10,
    default_rest_seconds: 120,
    is_active: 1
  },
  {
    id: 'EX_QUA_002',
    name: 'Agachamento frontal',
    muscle_group: 'Quadríceps',
    secondary_muscles: 'Core, Glúteos',
    equipment: 'Barra',
    exercise_type: 'Força/Hipertrofia',
    difficulty: 'Avançado',
    description: 'Barra apoiada nos deltoides anteriores enfatizando os quadríceps e postura ereta.',
    instructions: 'Cotovelos altos apontando para frente, agache mantendo o tronco estritamente vertical.',
    default_sets: 4,
    default_min_reps: 6,
    default_max_reps: 10,
    default_rest_seconds: 120,
    is_active: 1
  },
  {
    id: 'EX_QUA_003',
    name: 'Agachamento no Smith',
    muscle_group: 'Quadríceps',
    secondary_muscles: 'Glúteos',
    equipment: 'Máquina Smith',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Barra guiada que facilita posicionar os pés mais à frente para isolar quadríceps.',
    instructions: 'Destrave a barra e agache de forma controlada empurrando o chão com os calcanhares.',
    default_sets: 4,
    default_min_reps: 8,
    default_max_reps: 12,
    default_rest_seconds: 90,
    is_active: 1
  },
  {
    id: 'EX_QUA_004',
    name: 'Agachamento sumô',
    muscle_group: 'Quadríceps',
    secondary_muscles: 'Adutores, Glúteos',
    equipment: 'Barra / Halter',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Pés bem afastados com pontas rodadas para fora.',
    instructions: 'Desça com os joelhos acompanhando a direção dos pés, sentindo adutores e quadríceps.',
    default_sets: 3,
    default_min_reps: 8,
    default_max_reps: 12,
    default_rest_seconds: 90,
    is_active: 1
  },
  {
    id: 'EX_QUA_005',
    name: 'Agachamento hack',
    muscle_group: 'Quadríceps',
    secondary_muscles: 'Glúteos',
    equipment: 'Máquina Hack',
    exercise_type: 'Hipertrofia',
    difficulty: 'Intermediário',
    description: 'Apoio nas costas com ângulo inclinado, isolamento brutal dos quadríceps.',
    instructions: 'Desça profundo com joelhos alinhados aos pés e empurre sem travar a articulação no topo.',
    default_sets: 4,
    default_min_reps: 8,
    default_max_reps: 12,
    default_rest_seconds: 90,
    is_active: 1
  },
  {
    id: 'EX_QUA_006',
    name: 'Hack squat',
    muscle_group: 'Quadríceps',
    secondary_muscles: 'Glúteos',
    equipment: 'Máquina Hack',
    exercise_type: 'Hipertrofia',
    difficulty: 'Intermediário',
    description: 'Agachamento guiado em trilho inclinado.',
    instructions: 'Mantenha a lombar colada no encosto e flexione os joelhos profundamente.',
    default_sets: 4,
    default_min_reps: 8,
    default_max_reps: 12,
    default_rest_seconds: 90,
    is_active: 1
  },
  {
    id: 'EX_QUA_007',
    name: 'Leg press 45°',
    muscle_group: 'Quadríceps',
    secondary_muscles: 'Glúteos, Panturrilha',
    equipment: 'Máquina Leg Press 45',
    exercise_type: 'Força/Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Permite mover cargas expressivas com total segurança lombar.',
    instructions: 'Pés no meio da plataforma, desça até 90 graus ou mais sem descolar o quadril do banco e empurre.',
    default_sets: 4,
    default_min_reps: 10,
    default_max_reps: 12,
    default_rest_seconds: 90,
    is_active: 1
  },
  {
    id: 'EX_QUA_008',
    name: 'Leg press horizontal',
    muscle_group: 'Quadríceps',
    secondary_muscles: 'Glúteos',
    equipment: 'Máquina',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Empurrada horizontal com placas de peso selecionáveis.',
    instructions: 'Empurre a plataforma de forma fluida e retorne controlando a carga.',
    default_sets: 3,
    default_min_reps: 10,
    default_max_reps: 15,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_QUA_009',
    name: 'Leg press unilateral',
    muscle_group: 'Quadríceps',
    secondary_muscles: 'Glúteos',
    equipment: 'Máquina Leg Press',
    exercise_type: 'Hipertrofia',
    difficulty: 'Intermediário',
    description: 'Corrige assimetrias de força e volume entre as pernas.',
    instructions: 'Posicione um pé no centro da plataforma e execute com amplitude e ritmo controlado.',
    default_sets: 3,
    default_min_reps: 10,
    default_max_reps: 12,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_QUA_010',
    name: 'Cadeira extensora',
    muscle_group: 'Quadríceps',
    secondary_muscles: 'Reto femoral',
    equipment: 'Máquina',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Isolamento estrito dos quatro feixes do quadríceps.',
    instructions: 'Costas bem apoiadas, estenda os joelhos até alinhar as pernas e segure 1 segundo no pico.',
    default_sets: 4,
    default_min_reps: 12,
    default_max_reps: 15,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_QUA_011',
    name: 'Extensora unilateral',
    muscle_group: 'Quadríceps',
    secondary_muscles: 'Reto femoral',
    equipment: 'Máquina',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Isolamento unilateral para equilíbrio de força articular.',
    instructions: 'Trabalhe uma perna de cada vez com foco no vasto medial e reto femoral.',
    default_sets: 3,
    default_min_reps: 12,
    default_max_reps: 15,
    default_rest_seconds: 45,
    is_active: 1
  },
  {
    id: 'EX_QUA_012',
    name: 'Agachamento búlgaro',
    muscle_group: 'Quadríceps',
    secondary_muscles: 'Glúteos, Adutores',
    equipment: 'Halteres / Banco',
    exercise_type: 'Força/Hipertrofia',
    difficulty: 'Intermediário',
    description: 'Um dos mais potentes construtores de pernas e glúteos unilateral.',
    instructions: 'Um pé apoiado atrás no banco, desça o joelho de trás em direção ao chão e empurre com o calcanhar da frente.',
    default_sets: 3,
    default_min_reps: 8,
    default_max_reps: 12,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_QUA_013',
    name: 'Afundo',
    muscle_group: 'Quadríceps',
    secondary_muscles: 'Glúteos',
    equipment: 'Halteres / Peso Corporal',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Passo estático descendo o joelho posterior até quase encostar no chão.',
    instructions: 'Dê um passo à frente, flexione ambos os joelhos em 90 graus e suba.',
    default_sets: 3,
    default_min_reps: 10,
    default_max_reps: 12,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_QUA_014',
    name: 'Afundo com halteres',
    muscle_group: 'Quadríceps',
    secondary_muscles: 'Glúteos',
    equipment: 'Halteres',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Afundo segurando halteres nas mãos para sobrecarga progressiva.',
    instructions: 'Segure os halteres ao lado do corpo e realize o afundo mantendo o tronco ereto.',
    default_sets: 3,
    default_min_reps: 10,
    default_max_reps: 12,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_QUA_015',
    name: 'Afundo no Smith',
    muscle_group: 'Quadríceps',
    secondary_muscles: 'Glúteos',
    equipment: 'Máquina Smith',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Permite focar apenas em empurrar sem se preocupar com o equilíbrio lateral.',
    instructions: 'Barra sobre o trapézio, posicione um pé à frente e outro atrás, e execute a descida.',
    default_sets: 3,
    default_min_reps: 10,
    default_max_reps: 12,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_QUA_016',
    name: 'Passada',
    muscle_group: 'Quadríceps',
    secondary_muscles: 'Glúteos, Posterior',
    equipment: 'Halteres / Barra',
    exercise_type: 'Hipertrofia',
    difficulty: 'Intermediário',
    description: 'Caminhada com passos largos flexionando os joelhos em 90 graus.',
    instructions: 'Avance com um passo largo, flexione até o joelho de trás raspar no solo e dê o próximo passo.',
    default_sets: 3,
    default_min_reps: 10,
    default_max_reps: 14,
    default_rest_seconds: 75,
    is_active: 1
  },
  {
    id: 'EX_QUA_017',
    name: 'Passada andando',
    muscle_group: 'Quadríceps',
    secondary_muscles: 'Glúteos, Condicionamento',
    equipment: 'Halteres',
    exercise_type: 'Hipertrofia/Resistência',
    difficulty: 'Intermediário',
    description: 'Walking lunge dinâmico pelo salão.',
    instructions: 'Mantenha o ritmo constante e controle a descida para proteger as articulações.',
    default_sets: 3,
    default_min_reps: 12,
    default_max_reps: 16,
    default_rest_seconds: 90,
    is_active: 1
  },
  {
    id: 'EX_QUA_018',
    name: 'Step-up',
    muscle_group: 'Quadríceps',
    secondary_muscles: 'Glúteos',
    equipment: 'Caixa / Banco / Halteres',
    exercise_type: 'Hipertrofia/Funcional',
    difficulty: 'Iniciante',
    description: 'Subida no banco ou caixa, fortalecendo joelhos e estabilidade.',
    instructions: 'Pise firme no banco e impulsione o corpo para cima usando predominantemente a perna apoiada.',
    default_sets: 3,
    default_min_reps: 10,
    default_max_reps: 12,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_QUA_019',
    name: 'Agachamento goblet',
    muscle_group: 'Quadríceps',
    secondary_muscles: 'Glúteos, Core',
    equipment: 'Halter / Kettlebell',
    exercise_type: 'Hipertrofia',
    difficulty: 'Iniciante',
    description: 'Excelente para aprender profundidade de agachamento com peso no peito.',
    instructions: 'Segure o peso verticalmente colado ao peito e agache abrindo os joelhos.',
    default_sets: 3,
    default_min_reps: 10,
    default_max_reps: 15,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_QUA_020',
    name: 'Agachamento no landmine',
    muscle_group: 'Quadríceps',
    secondary_muscles: 'Glúteos, Core',
    equipment: 'Barra Landmine',
    exercise_type: 'Hipertrofia',
    difficulty: 'Intermediário',
    description: 'A trajetória em arco guia o movimento natural do quadril sem sobrecarga na coluna.',
    instructions: 'Segure a ponta da barra no peito e agache afundando o quadril.',
    default_sets: 3,
    default_min_reps: 10,
    default_max_reps: 12,
    default_rest_seconds: 60,
    is_active: 1
  },
  {
    id: 'EX_QUA_021',
    name: 'Sissy squat',
    muscle_group: 'Quadríceps',
    secondary_muscles: 'Tendão Patelar',
    equipment: 'Banco Sissy / Peso Corporal',
    exercise_type: 'Hipertrofia',
    difficulty: 'Avançado',
    description: 'Isolamento extremo do reto femoral através de flexão de joelho com extensão de quadril.',
    instructions: 'Incline o tronco para trás flexionando os joelhos para frente e empurre retornando.',
    default_sets: 3,
    default_min_reps: 8,
    default_max_reps: 12,
    default_rest_seconds: 60,
    is_active: 1
  }
];
